### ISSUE TITLE
Externě volaný script na idnes.cz

### ISSUE THREAD

**Issue by Rimatara** [tomasko126/easylistczechandslovak#109]
Jak pomocí uBlock zablokovat externě volaný script:
[https://www.2i.cz/images/2017/11/28/iDNES.jpg](url)

případně zablovat všechny obrázky typu pozadí ?

`<script language="JavaScript">
New Ads.Standardflash({ "link": "https://praha.idnes.cz/nyBXIkfGhT9-_LQl-ti_kxOB2Ty9ytIHwcYhfyfg-m/rYwJcY506F6b7kVU6JdfzVAY4_8gwnmlE5oCjlgYLaSa_2V/oKUxtiqQV29JXlxlQ_-hiyegiJEIDFnm7Sa-NxihILjnr/NlS1,JCLmcohxBOsivCJszxvlCRjKeA530ptxvlEI/A9edFlA7jy_EjjToVzF0pSXKS9L9Yx8Hlx50Emv0X/l-14kv0Hqm_lLGTd7Hg/1bJ_UM/dEagP4Rw111,EZPA1Pb3tAny", "obrazek": "https://praha.idnes.cz/nyV9vZE6jzgsy0zn9JRdHV8yDcvfTnxp9f5SlPEnojC/xl0BMG9i.zvRT4yo0gg2joMl,63SGJw/5fA0d41,vTce7nFDRsGhcaioX8GZHPHTg0bKbmXFFSso-D-s6Qny ", "rozmery": [998,200], "transparentní": false}); Ads.Branding({ "link ": "https://praha.idnes.cz/nyBXIkfGhT9-_LQl-ti_kxOB2Ty9ytIH/wcYhfyfg-mrYwJcY506F6b7kVU6JdfzVA/Y4_8gwnmlE5oCjlgYLaSa_2V/oKUxtiqQV29JXlxlQ_-hiyegiJEIDFnm7Sa-NxihILjnr/NlS1,JCLmcohx80sivCJszxvlCR/jKeA530ptxvlEIA9edF1A7jy_Ejj/ToVzF0pSXKS9L9Yx8Hlx50Emv0Xl-14kv0Hqm_lLGTd7HgMbJ_U/MdEagP4Rw111,EZPA1Pb3tAny", "target": "_blank", "body": "https://praha.idnes.cz/nyFTpjZGgE23Vxeylkwsvvi0hqscjrXiI/Z3qqsmubshAn8Gzse2t4eza_g6y/Scdt4\.iUDG8-fZ-E4xaQSpylmTZXsusjFmrAxkbZDdrp/mLUTnycentrumpraha_black-friday_branding_2000x1200_cz--final--0A02021200.jpg", "double-board": true_, "fixni-main": false, "fixni-body": false });
</script>`

**Comment by vobruba-martin** [comment]
Asi bych zacal tady: https://github.com/gorhill/uBlock/wiki/Inline-script-tag-filtering

Bohuzel tyhle pravidla neni mozne pridat do EasyListu, protoze rozbiji funkcnost ABP :(

**Comment by Rimatara** [comment]
Díky, vypadá to, že stačí pro uBlock použít vlastní filtr: idnes.cz##script:contains(new)
