### ISSUE TITLE
uBlock filtry

### ISSUE THREAD

**Issue by vobruba-martin** [tomasko126/easylistczechandslovak#115]
Vzhledem k tomu, ze filtry pro uBlock rozbijeji fungovani ABP pro Chrome/Operu, neni vhodne je pridavat do `filters.txt`. Napada me tedy, jestli by bylo reseni, kdyby doslo k vytvoreni filtru primo pro uBlock.

Je otazka, jakym zpusobem by to pripadne mohlo fungovat:

1) `filters_ublock.txt` by obsahoval stejny obsah jako `filters.txt` + pravidla pro uBlock.
 - Bylo by to horsi na spravu, protoze by bylo pro kazde pravidlo nutne upravovat 2 soubory.
 - Asi by bylo snazsi do uBlocku prosadit jen zmenu URL.

2) `filters_ublock.txt` by obsahoval jen pravidla pro uBlock.
 - Snazsi na spravu.
 - Nevim, jakym zpusobem by se to dalo nejak rozumne prosadit do uBlocku.

/cc @tomasko126 @Aslanex

**Comment by vobruba-martin** [comment]
Zrovna koukam, ze diky commitu b41e211dc07f6c5501a65b313a7818743dbed340, mam Chrome s ABP na `zive.cz` i `mobilmania.cz` opet plne reklam.

**Comment by MilanKK** [comment]
Tento filtr:
`mobilmania.cz,zive.cz##.ar-detail + div`
blokne psaní příspěvků na zive.cz

**Comment by vobruba-martin** [comment]
Koukal jsem na zdroj uBlocku a PR pro zmenu URL by slo vytvorit snadno. Sel bych tedy 1. cestou:
- Vytvorit kopii stavajich filtru.
- Poslat do uBlocku PR pro zmenu URL.
- Vycistit stavajici filtry od uBlock pravidel.

**Comment by Aslanex** [comment]
To by neměl být problém, co na to @tomasko126 ?

**Comment by tomasko126** [comment]
@Aslanex @vobruba-martin Súhlasím s 1. možnosťou.

**Comment by tomasko126** [comment]
@MilanKK Daný filter bol odstránený v 0a1f9f0fd5a8bd4bfa24a27f9b0702b9082aac09.

**Comment by vobruba-martin** [comment]
@tomasko126 
To asi uplne neni stastne reseni, protoze ABP specificke filtry umi uBlock interpretovat spravne. Jsou tam nejake vyjimky, ale to bude chtit resit pro kazde pravidlo zvlast. Momentalne by doslo k tomu, ze veci, ktere do ted v uBlocku byly blokovany spravne, prestanou byt v uBlocku blokovany kvuli absenci tech ABP specifickych filtru.

Zkusim to kdyztak projit, jakmile si najdu chvili a take vytvorim PR v uBlock repozitari.

**Comment by vobruba-martin** [comment]
PR v uBlock repozitari je zde: https://github.com/gorhill/uBlock/pull/3312

**Comment by tomasko126** [comment]
@vobruba-martin Všetky ABP špecifické filtre v zozname filtrov som pridal na koniec súboru ```filters.txt```. Je niekde (pravdepodobne v repo uBlocku) zoznam ABP špecifických filtrov, ktoré sa automaticky konvertujú v uBlocku na uBlock pravidlá?

**Comment by vobruba-martin** [comment]
Ja to chapu tak, ze uBlock by mel podporovat vsechny ABP syntaxe. Viz https://github.com/gorhill/uBlock/wiki/Static-filter-syntax

Kazdopadne vim minimalne o jedne vyjimce:
`:-abp-has()` se sice automaticky konvertuje na `:has()`, ale v uBlocku muze `:has()` obsahovat pouze validni CSS selector kvuli pripadne budouci kompatibilite v browserech. V ABP muze `:-abp-has()` obsahovat napr. regularni vyraz nebo dalsi ABP specificky selector. Zalezi tedy pripad od pripadu, kdy muze jedno pravidlo fungovat v obou blokatorech a kdy je potreba to vyresit pro kazdy z nich zvlast.

**Comment by vobruba-martin** [comment]
V 51f2c3cefaffbe1564d0f519e34481995fcc5c4c jsem synchronizoval uBlock filtry. Vsechny ABP specificke filtry, ktere tam mame, by mely byt kompatibilni s uBlockem, protoze `:-abp:has()` pravidla vzdy obsahuji validni CSS selector.

**Comment by vobruba-martin** [comment]
Tak myslim, ze mame vyreseno :-)
