### ISSUE TITLE
idnes.cz nefiltruje background reklamu

### ISSUE THREAD

**Issue by Vict0rC** [tomasko126/easylistczechandslovak#124]
Zdravim,
na idnes.cz se mi nefiltruje background reklama, konkretne ji zobrazuje element:
`<style id="branding-stylesheet">
html.klikaci-body body { background: url('https://www.idnes.cz/HkJ4mYh12McY-cxQQ0Yk06E1jrlFRtykUafD0TLAJPiHnAz/-NoueLBmH45bhVSi6F56tud-4eRAaV1/BZjAoNRErRxKRupi5hdTUK/3mwW-4cCCoRGehMLmtlUuQjdgTX4zjnHk') no-repeat scroll 50% 0, url('https://www.idnes.cz/HkWRaidALrW62HLZvndV8_p8XIvQV_eOJUkrEUtHF09X/ehTKkPK--vaV2QiRhkHdgU4RoSzNr98n2L/eHv5aoaKzauoppYSady-CCqSVg8OTKwI8wjsX57M/WiBk7VB2C0gHk') repeat-y scroll 50% 0px } html.klikaci-body #main {background:0}
.ahead { height: 217px; }
</style>`
Bohuzel se mi nedari vytvorit funkcni custom filtr k odstraneni celeho elementu <style id="branding-stylesheet">
pouzivam verzi filtru 08/12/2017
Diky za rady.
VicC

**Comment by vobruba-martin** [comment]
V uBlocku by mohl fungovat tento filtr: `idnes.cz##html.klikaci-body body:style(background:none !important;)`

Dej kdyztak vedet, jestli to zabere, ze bych ho pridal.

**Comment by MilanKK** [comment]
Já nejen na idnes používám:
`idnes.cz##html,body:style(background-image:none !important)`

**Comment by Vict0rC** [comment]
Diky moc MilanKK, oba filtry funguji perfektne
