### ISSUE TITLE
Novinky.cz

### ISSUE THREAD

**Issue by WalrusInAnus** [tomasko126/easylistczechandslovak#126]
S povoleným Adblockem je web částečně "rozsypaný", a reklamy i tak nejsou blokované.
![capture](https://user-images.githubusercontent.com/17233430/34391242-b1dc4ba8-eb44-11e7-9611-921b8ba65eb4.PNG)

**Comment by MilanKK** [comment]
Je možné, že je to rozsypané díky easyprivacy:
https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_trackingservers_international.txt
a filtru:
||dopc.cz^$third-party
hlásil jsem to tu:
https://github.com/easylist/easylist/commit/73e524a4872e5f76d0396c9107ee38af7f4e9444#diff-1a58c0a4c8e32e93aa7240cd96af3279
Jelikož jsou potřeba nejspíš jen obrázky, tak na to používám vlastní filtr:
@@dopc.cz$image 
nebudeš to pak mít rozsypané.
Platí to pro případ s cookies.
Každopádně pokud nepotřebuješ cookies pro web (např. nejsi přihlášený), tak je pro web blokuj, umí to každý prohlížeč defaultně a blokování reklam je pak dalepo pohodlnější a weby jsou daleko rychlejší.
Např. i s tím pokaženým filtrem z easyprivacy bys měl ten web OK.

**Comment by vobruba-martin** [comment]
Sam jsem to ted vyzkousel a problem na `novinky.cz` nebo `idnes.cz` opravdu zpusobuje EasyPrivacy. Jde tomu predejit pridanim vlastniho filtru `@@dopc.cz$image`, jak pise @MilanKK. Diky!

**Comment by WalrusInAnus** [comment]
@MilanKK Myslíš blokovat cookies kompletně, nebo jen pro konkrétní web (tedy pokud to jde)?

**Comment by MilanKK** [comment]
@WalrusInAnus Myslím konkrétně pro určitý web. Například já na novinkách a idnes nepíšu, takže se tam nepotřebuju přihlašovat, nepotřebuju tam mít tedy cookies, tak je prostě pro novinky a idnes zakážu.
V chrome to jde nastavit pro doménu druhého řádu a bere to pak myslím i domény třetího řádu. Ve firefoxu je to trošku horší, tam se to musí nastavovat zvlášť i pro domény třetího řádu a třeba na zive jich je tam celůkem dost. Takže bych si docela přál, aby se to daly blokovat cookies i v ublocku, proč to do něj ještě nepřidali? Jinak zkouším používat i uMatrix od stejného autora jako je uBlock Origin, a ten cookies blokovat svede, globálně, globálně pro doménu druhého řádu a poddomény, nebo jednotlivě.
