### ISSUE TITLE
Aktualne.cz obsahuje reklamu na skrz.cz

### ISSUE THREAD

**Issue by novjan** [tomasko126/easylistczechandslovak#127]

**Comment by vobruba-martin** [comment]
Byl by nejaky link/screen?

**Comment by lukasojd** [comment]
![screenshot-2018-1-4 lide budou dal vedet jak ministri hlasovali spory ve vlade ma i pres kritiku rozhodovat premier aktual](https://user-images.githubusercontent.com/3088025/34586473-6435df52-f1a4-11e7-9a37-91d28cbd59f1.png)

**Comment by mapx-** [comment]
```
/aktualne\.cz\/[0-9a-zA-Z]{30,}/$domain=aktualne.cz,script
aktualne.cz#?#.rtx-burn12 + DIV:-abp-contains(r.klama)
```
