### ISSUE TITLE
several major czech sites

### ISSUE THREAD

**Issue by mapx-** [tomasko126/easylistczechandslovak#128]
https://forums.lanik.us/viewtopic.php?f=108&t=39516

**Comment by MilanKK** [comment]
Nahlášeno je to na EasyPrivacy tu:
https://github.com/easylist/easylist/commit/73e524a4872e5f76d0396c9107ee38af7f4e9444#comments

**Comment by vobruba-martin** [comment]
This should be fixed in EasyPrivacy list.
