### ISSUE TITLE
na vstupenky.ticket-art.cz se blokují prvky stránky 

### ISSUE THREAD

**Issue by lukasojd** [tomasko126/easylistczechandslovak#129]
Toto pravidlo blokuje prvky stránky

.cz/img/banner$domain=~abecedaher.cz|~amnesty.cz|~hitech.instruktori.cz|~melcer.cz|~mironet.cz

https://vstupenky.ticket-art.cz/img/banner/banner_1000_thumb.jpg

**Comment by vobruba-martin** [comment]
Domena pridana do vyjimek. Diky!
