### ISSUE TITLE
zive.cz

### ISSUE THREAD

**Issue by jurask** [tomasko126/easylistczechandslovak#130]
Na zive.cz jsou blokovány regulérní obrázky, zatímco reklamy se vesele zobrazují

https://screenshots.firefox.com/nJcqJUs9ZxmfaXi4/www.zive.cz

**Comment by vobruba-martin** [comment]
Jake pravidlo ti to zpusobuje? Ja tam totiz obrazky vidim vporadku.

**Comment by Kisuke-CZE** [comment]
Podle me pomuze vymazat cookies pro domenu zive.cz. Oni tam maj nejaky JS, ktery se podle cookie rozhoduje jakou verzi stranky ti zobrazi. Me to taky jede OK, a to jsem zkousel zapnout EasyList (normalne nepouzivam).

Kazdopadne EasyList skryva zbytecne na zive cely sidebar pres `zive.cz##div.sky-wrapper`, kde jsou odkazy na nejake nejctenejsi jejich clanky, a dalsi celkem zajimave veci. Podle me v tom sidebaru bohate postaci schovat reklamy pomoci `zive.cz,mobilmania.cz##.ads`. Aspon me to funguje (ale mam asi bloknute i jine veci).

**Comment by petersaly** [comment]
@jurask @vobruba-martin boli tam pouzite pravidla pre uBlock https://github.com/tomasko126/easylistczechandslovak/pull/195  uz by to malo byt ok

@Kisuke-CZE zive.cz##div.sky-wrapper neskryva cely sidebar, je tam Aktuální zpravodajství, atd.
