### ISSUE TITLE
Novinky.cz znovu

### ISSUE THREAD

**Issue by WalrusInAnus** [tomasko126/easylistczechandslovak#133]
Tentokrát rozsypanou stránku nezpůsobuje Easyprivacy, ale Easylist. Resp. jak původní Easylist tak česká varianta.
Netuším, jak určit, co konkrétně. Vůbec filtrům v Adblocku nerozumím.

**Comment by vobruba-martin** [comment]
Jako rychly reseni doporucuju vypnout a vycistit cookies na domene novinky.cz.

**Comment by WalrusInAnus** [comment]
To funguje, ale zároveň to zablokuje videa.

**Comment by vobruba-martin** [comment]
Pouzivam uBlock Origin + blokovani cookies a videa mi to prehrava vporadku. Mozna problem v kombinaci s adblockem?

**Comment by WalrusInAnus** [comment]
Netuším co je uBlock Origin.
Nic s Adblockem nekombinuju.
Asi by to chtělo někoho, kdo používá Adblock. Tohle vyjádření "ale mně to funguje" je dost k ničemu.

**Comment by vobruba-martin** [comment]
Myslel jsem to tak, jestli neni problem samotnej adblock, ze ti videa nefunguji. V uBlocku mam zapnute stejne filtry (EasyList, EasyPrivacy, CZ/SK EasyList, + mnoho dalsich) a videa funguji.

Ono se taky tezko radi, kdyz nedokazes rict, ktere pravidlo ti zpusobuje problem.

**Comment by WalrusInAnus** [comment]
Aha.
Jak mám zjistit, o které pravidlo se jedná?

**Comment by WalrusInAnus** [comment]
Zkusil jsem nainstalovat Ublock, a reklamu sice blokuje, ale narozdíl od Adblocku po reklamě zůstávají na stránkách prázdná místa. Co s tím?

**Comment by WalrusInAnus** [comment]
Tak teď už nerozumím ničemu.
Aktualizoval jsem v uBlocku filtry, a Novinky jsou reklam plné odshora dolů včetně pozadí.

**Comment by WalrusInAnus** [comment]
Update: Reklama se někdy zobrazí a někdy ne, ale blokovaná je tak ve 20% případů. Někdo v diskuzi o uBlocku tvrdil, že na stránce je nějaký script, který detekuje blokování reklamy.
Mohl by to někdo ověřit?
Fakt už nevím.
![untitled](https://user-images.githubusercontent.com/17233430/35085350-32a71b46-fc20-11e7-9a6e-f3aa6b3d80d2.png)

**Comment by KoBilla** [comment]
@vobruba-martin pouzivas default blokovani cookie co je v Chrome? Nebo nejaky plugin a jaky? Pri zablokovani vseho je problem s prihlasovanim a obcas nejakou funkcnosti.

**Comment by MikeRosoft** [comment]
Stránka novinky.cz poměrně agresivně vkládá reklamy na stránku, a navíc zablokování/zneviditelnění iframů má často za následek, že přestanou fungovat styly. Momentálně následující pravidla ruším:

```
!Pravidlo má za následek ztrátu stylů
||novinky.cz/*novinky.cz$subdocument
!Pravidlo blokuje odkaz na seznam.cz v hlavičce stránky
novinky.cz###seznamLink
!Pravidlo blokuje odkaz na profimedia.cz v zápatí
novinky.cz##a[href*="imedia.cz"]
```

Dále používám kombinaci AdBlock pravidel:
```
novinky.cz###adSkyBottomWrapper
novinky.cz###rightColumn
novinky.cz###middleLdrBox
novinky.cz##.ban
novinky.cz##.cont
novinky.cz###komercni
novinky.cz###container-eta
novinky.cz##.jeban
novinky.cz##A#seznamLink[target="_top"]
novinky.cz##IMG[class*="gojkuln"]
novinky.cz##.glami-newrap
novinky.cz##A#loginLink[target="_top"]
novinky.cz##[class*="adform"]
novinky.cz##IMG[style*="cursor:pointer"]
novinky.cz###adNovinkyNativni
@@||novinky.cz/*/www.novinky.cz/reklama.html$subdocument
```
A stylu pro extenzi "Stylish":
```
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("novinky.cz")
{
  body { background-image: none !important; } /* Block advertising backgrounds */
  iframe[class*="gojkuln"]
  {
    height:0px !important;
    width:0px !important;
    overflow: hidden !important;
  }
}
```

**Comment by MikeRosoft** [comment]
Můj aktuální styl na novinky.cz pro extenzi Stylish je:

```
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("novinky.cz")
{
  body { background-image: none !important; } /* Block advertising backgrounds */
  
  iframe[class*="gojkuln"],
  *[style*="width: 970px"],
  *[style*="position: fixed"],
  *[style*="position:fixed"],
  *[style*="position: absolute"],
  *[style*="position:absolute"],
  .sssp-posCont
  {
    height:0px !important;
    width:0px !important;
    overflow: hidden !important;
    background-image: none !important;
  }
  
  #main_body_top 
  {
    margin-top: 5px !important;
  }
  
  body#novinky-cz
  {
    padding: 0 !important;    
  }
  
}
```

**Comment by WalrusInAnus** [comment]
To vůbec nevím co znamená.
Mohl by někdo prosím aktualizovat ty filtry?
