### ISSUE TITLE
http://bazar.hunting-shop.cz/

### ISSUE THREAD

**Issue by WalrusInAnus** [tomasko126/easylistczechandslovak#134]
Reklamy mezi inzeráty, a ve sloupci vlevo (dvě nad sebou).

**Comment by vobruba-martin** [comment]
Jedna o promovani sebe sama, coz podle definice EasyListu neni reklama, ktera by mela byt blokovana.

**Comment by WalrusInAnus** [comment]
Aha.
Můžeš mi poradit, který filtr v uBlocku použít, aby zmizely všechny reklamy mezi inzeráty? Nějak na to nemůžu přijít. Vždycky zmizí jen jeden.

**Comment by vobruba-martin** [comment]
Zkus tyhle 2 filtry:

```
bazar.hunting-shop.cz##div.zbozi_okno + span
||bazar.hunting-shop.cz/__userdata/bannery/
```

**Comment by WalrusInAnus** [comment]
Zkusím.
Vysvětli mi ale, jaks na to přišel. Když v uBlocku otevřu Element picker, v tom okně s filtry nic takovýho není.
