### ISSUE TITLE
url /slevy/

### ISSUE THREAD

**Issue by evromalarkey** [tomasko126/easylistczechandslovak#135]
Z jakého důvodu je ve filtru url na /slevy/ ? Tady se snad nejedná o žádnou reklamu apod. ?
Tohle nám docela dělá paseku při zobrazení stránky s produktama která má url /slevy/, kde requesty směřují přes service worker. AdBlock blokne request service workeru a ten si myslí že je offline a zobrazí chybnou stránku.

**Comment by vobruba-martin** [comment]
Nejaka URL s ukazkou?

**Comment by evromalarkey** [comment]
např. https://www.rendl.cz/slevy/
