### ISSUE TITLE
idnes.cz a subdomény: tab při otevření na čas zmrzne

### ISSUE THREAD

**Issue by tulak2004** [tomasko126/easylistczechandslovak#137]
V MS Edge s uBlock Origin po zadání www.idnes.cz (a subdomén) tab na cca 10 sekund zamrzne, a pak teprve se stránka nahraje. 

Stránky mají embedded skript, který mimo jiné otevírá synchronní XmlHttpRequest, a než request skončí, je tab zamrzlý. 
```
//z technet.idnes.cz/, řádek 4
	function y(n, e) {
		var t = Number("0") && Math.random() < .2 ? "POST" : "GET",
		r = new XMLHttpRequest;
		r.open(t, n, !1),
		r.send(),
		200 === r.status && e(r)
	}
```

Zkoušel jsem bloknout všechny XmlHttpRequesty, ale to rozhodí styly. 
||*$xmlhttprequest,domain=idnes.cz

Bohužel mi syntaxe AdBlock (a uBlock Origin) rules vůbec není jasná. Uměl byste někdo pomoci?

**Comment by tomasko126** [comment]
@tulak2004 Zdravím, vyskytuje sa stále tento problém v prehliadači MS Edge?

**Comment by tulak2004** [comment]
Dobrý den, mám za to, že se přestal vyskytovat. V mezičase jsem také přešel z uBlock Origin na AdGuard, a tam se mi problém určitě nevyskytuje. Koukám že mám zapnutý jen AdGuard Base Filter, který zahrnuje i EasyList, a ve zdroji vidím i idnes. Každopádně za mě problém vyřešen. Zdravím, Karel

______________________________________________________________
