### ISSUE TITLE
dobra-reklama.com

### ISSUE THREAD

**Issue by datelvivaldi** [tomasko126/easylistczechandslovak#143]
Muj zakaznik si koupil domenu dobra-reklama.com. Prosim o zarazeni na whitelist.

**Comment by tomasko126** [comment]
Zdravím, tento problém sme zaznamenali taktiež u iných doménach, ktorých názov končil na reklama.{sk/cz} alebo na reklamy.{sk/cz}. Nakoľko filtre ```reklama.``` a ```reklamy.``` sú príliš generické, boli odstránené - 5c3e60b70c258fdb259e8862fc23cb460847676.
