### ISSUE TITLE
Czech Publisher Exchange

### ISSUE THREAD

**Issue by trumpeta** [tomasko126/easylistczechandslovak#159]
Nazdar, už jsem to poslal do bugtrackeru uBlocku ale nějak si s tím neví rady. Od června používají hlavní české weby externí framework na eliminaci adblockerů, co hůř kromě toho že se všude zobrazují reklamy, při detekci ABP, uBO, AdGuardu se aktivuje kurvítko které zabrání dokončení načítání stránek a to má zase další konsekvence, jako že nejde použít element picker pro interaktivní vytvoření kosmetických filtrů. Všechny dotyčné weby patří pod `https://www.cpex.cz/` takže to bude asi jejich nástroj.
Poskládal jsem si prozatimní seznam kosmetických skriptů které blokují většinu reklam na těchto webech, ale není to ideální řešení protože kosmetické filtry zpomalují načítání stránek a reklamu schovají až když je vytvořená, nehledě an to že pořád nejde dokončit načítání stránek.  Bude tedy spíš potřeba eliminovat ty skripty které dodatečně vkládají reklamy do stránek a celkově zpomalují práci se stránkami.

Seznam dotčených serverů:

`https://www.idnes.cz/`
`https://www.novinky.cz/`
`https://www.aktualne.cz/`
`https://ihned.cz/`
`https://www.info.cz/`
`https://www.blesk.cz/`
`https://www.ahaonline.cz/`
`https://www.extra.cz/`
`https://www.super.cz/`
`https://www.zive.cz/`
`http://isport.blesk.cz/`
`http://www.auto.cz/`
`http://www.reflex.cz/`
`https://www.e15.cz/`
`https://avmania.e15.cz/`
`https://www.maminka.cz/`
`https://www.mobilmania.cz/`
`https://www.centrum.cz/`
`http://atlas.centrum.cz/`
`http://www.volny.cz/`
`http://tiscali.cz/`
`http://games.tiscali.cz/`
`https://www.osobnosti.cz/`
`http://nedd.tiscali.cz/`
`https://cestovani.tiscali.cz/`

[uBlockOrigin/uBlock-issues#2790](https://github.com/uBlockOrigin/uAssets/issues/2790)
[uBlockOrigin/uBlock-issues#53](https://github.com/uBlockOrigin/uBlock-issues/issues/53)

**Comment by vobruba-martin** [comment]
Muzes tady vytvorit PR s temi filtry, at je muzeme pridat?

**Comment by vobruba-martin** [comment]
Ja to z toho issue sice muzu prepsat, ale pak bych byl ja veden jako autor toho commitu a ne ty.

BTW ja uz jsem si kvuli tomu jejich reseni na uvedenych webech vypnul cookies uplne. To pomaha krasne.

**Comment by trumpeta** [comment]
Jsem se díval zběžně do struktury jedné stránky a většinu co blokují už blokoval filtr z czech listu.
Aktuální verze ale s tím že část může být redundantní, nemám moc času znovu všechno porovnávat po zablokování toho ad skriptu. 

```
cz##div.ads
cz###Leader-1
cz##div.leaderboard
cz###HalfPageTop
cz###HalfPageBottom
cz##[id^="Billboard-bottom-"]
cz##[id^="Skyscraper-"]
cz##[id^="Commercial-"]
cz##[id^=Square-"]
cz##[id^="PR-perex-"]
cz##[id^="PR-premium-"]
cz##[id^="Fullbanner-"]
cz##[id^="Leaderboard-"]
cz###Partner-statistik
cz##[id^="Mobile-rectangle-"]
cz##[id^="510x90-klub-"]
cz###Rectangle480-1
cz###Rectangle-left-1
cz###Rectangle-right-1
cz###Cileni-na-znacku-1
cz###Otvirak-1
cz###Komercni-tip
cz###idvert

cz##div[class]:has(> div#Leader-1)
cz##div[class]:has(> div#HalfPageTop)
cz##div[class]:has(> div#HalfPageBottom)
cz##div[class]:has(> div#Billboard-bottom-1)
!cz##div[class]:has(> div.banner)
cz##div[class$="banner"]
cz##div[class$="column"]:has(> div[class$="items"])
/hb/cpex-hb-sas-cnc.js|$script
/skin/v2/cpex-skin.js|$script

idnes.cz##div#main > rale[class]
idnes.cz###ads-sticky
idnes.cz##:xpath(//div[@*[starts-with(name(), 'data-')]])
idnes.cz##script:inject(set-constant.js, Ads.ok, true)
/idnes\.cz\/[\w-_]{30,}/$domain=idnes.cz,script
||1gr.cz/data/selfboxy/Akcniceny/*$image,domain=idnes.cz

zive.cz##div#br-192-018
info.cz##div#topSite
info.cz##div#leader_board
info.cz##div[class]:has(> div[class~="sticky-content"])
info.cz##div.article-advertisement
||info.cz/*.mp4|
reflex.cz##div#topSite
maminka.cz##div#content-lead
blesk.cz##div#ads-iframe
ahaonline.cz##div[id]:has(> div[id$="wrapper"][class$="anim"])

super.cz##div[class]:has(> div[class] > iframe[id^="im-"])
super.cz##div[id^="adPlachta"]

extra.cz##.centered.ad-leaderboard.ad
extra.cz##div.container:has(> div[class] > div[class] > div.ads:last-child)

centrum.cz##div[class="dolni-amplion clearfix"]
aktualne.cz##body > div > div > div > div[class]:has(> div[class] > div[class]:has-text(r.klama))
atlas.centrum.cz,www.volny.cz##.row.eHKepp.sc-eMigcr
tiscali.cz##div.wrap-advert
tiscali.cz##div[class~="btitle-right"]
games.tiscali.cz##[class]:has(> div[class][style="display:block/*ahoj*/!important"])
games.tiscali.cz##div[class][style="display:block/*ahoj*/!important"]
osobnosti.cz##div.hide-screenbot
osobnosti.cz##div.box.side-ad
osobnosti.cz##div[class~="box"]:has(> div[class] > div.sticky)
osobnosti.cz##div[class^="box "]:has(> div[id][class])
osobnosti.cz##div[id^="leader-bottom-"]:has(> div#lbttm)

```

**Comment by trumpeta** [comment]
Filtr přidaný do czechlistu už je blokován vydavatelem. Chce to nějaké trvalejší řešení, na to nedočítání stránek jsem alergický.

- zákaz cookies není přijatelné řešení protože cookie obsahují i např. přizpůsobení zobrazení nebo přihlášení k účtu

- dodatečná nefunkčnost stránek při detekci adblockeru zaznamenána u článků na `avmania.e15.cz` (při rozkliknutí galerie se obrázek okamžitě překryje točícím kolečkem)

**Comment by addisr** [comment]
Zavírám issue jelikož tohle už nějakou dobu aktuální filtry blokují.
