### ISSUE TITLE
TN.CZ - nehrajou videa 

### ISSUE THREAD

**Issue by trumpeta** [tomasko126/easylistczechandslovak#161]
Nazdar, v ublocklistu je tato výjimka 

```
! https://github.com/uBlockOrigin/uAssets/issues/523
||adserver.adtech.de/?advideo/3.0/$xmlhttprequest,important,redirect=nooptext,domain=nova.cz
||pro.hit.gemius.pl^$script,redirect=noopjs,domain=nova.cz
@@||adserver.adtech.de^$xmlhttprequest,domain=tn.nova.cz
@@||static.cz.prg.cmestatic.com/static/shared/app/videojs/plugins/*$script,domain=nova.cz
@@||pro.hit.gemius.pl/gplayer.js$script,domain=nova.cz
```
nicméně ta nefunguje když má uživatel nainstalovány MVPS hosts.
Jde vymazat ty dvě domény z MVPS ale je to už zásah který se musí provádět při každé aktualizaci MVPS.
Chtěl bych to ošetřit na úrovni skriptu.
Přehrývač obsluhuje externí skript [https://static.cz.prg.cmestatic.com/static/shared/app/player/player.min.js](https://static.cz.prg.cmestatic.com/static/shared/app/player/player.min.js)

Vlastní adblock detekce je funkcí _detectAdblock v objektu Player:

```
{
            key: "_detectAdblock",
            value: function _detectAdblock() {
                if (!__WEBPACK_IMPORTED_MODULE_0_global_window___default.a.location.origin) {
                    __WEBPACK_IMPORTED_MODULE_0_global_window___default.a.location.origin = __WEBPACK_IMPORTED_MODULE_0_global_window___default.a.location.protocol + "//" + __WEBPACK_IMPORTED_MODULE_0_global_window___default.a.location.hostname + (__WEBPACK_IMPORTED_MODULE_0_global_window___default.a.location.port ? ":" + __WEBPACK_IMPORTED_MODULE_0_global_window___default.a.location.port : "")
                }
                return new Promise(function(res, rej) {
                    __WEBPACK_IMPORTED_MODULE_2_jquery___default.a.ajax({
                        type: "GET",
                        url: "https://adserver.adtech.de/?advideo/2.0/1045.1/0/0/-1/noperf=1;cc=2;header=yes;cookie=yes;adct=204;alias=video_nova_xxx;vidAS=pre_roll;vidbreaknum=1;vidbreaklen=5;cors=yes;acao=" + escape(__WEBPACK_IMPORTED_MODULE_0_global_window___default.a.location.origin) + ";misc=1430751937274;vidRTV=2.0.1;vidnofmt=yes;vidRT=VAST_APVSCL",
                        success: function success() {
                            __WEBPACK_IMPORTED_MODULE_3_video_js___default.a.log("Adblock not present. Continue.");
                            res()
                        },
                        error: function error() {
                            __WEBPACK_IMPORTED_MODULE_3_video_js___default.a.log("Adblock active. Quit.");
                            rej(new Error("adblock"))
                        }
                    })
                }
                )
            }
        }
```

a volaná je z initu 
`if (_this7._options.ads && _this7._options.adblock) return _this7._detectAdblock();`

Takže stačí pomocí skriptletu nějak změnit hodnotu _this7._options.adblock na false nebo vynechat volání funkce ._detectAdblock(). Jde to?

**Comment by vobruba-martin** [comment]
Pokud by to bylo pod nejakym globalnim objektem, tak by to melo jit alespon ve FF. Hodis sem nejakej priklad stranky, kde se tohle nachazi?

**Comment by vobruba-martin** [comment]
Jeste me napada, jestli by nebylo mozny vytvorit defuser, ktery pomoci `jQuery.ajaxTransport()` bude tu testovaci URL zabijet a zaroven se to tvarilo, ze doslo k uspesnemu requestu.

**Comment by trumpeta** [comment]
jakýkoliv článek na tn.nova.cz, např.
`http://tn.nova.cz/clanek/stoji-se-v-praze-i-u-prostejova-hromadne-nehody-blokuji-dopravu.html`

změna _this7._options.adblock na false skutečně kontrolu adblocku vyřadí takže přehrávač hraje
zdánlivě jednoduchá úprava ale 
`nova.cz##script:inject(set-constant.js, Player._defaultOptions.adblock, false)`
nefunguje
