### ISSUE TITLE
Redundant leading space in subscription file

### ISSUE THREAD

**Issue by martinrotter** [tomasko126/easylistczechandslovak#17]
Your subscription file starts with " [Adblock Plus 2.0]" (note the space), but I guess it should start with "[Adblock Plus 2.0]" (without the space). This bug prevents this subscription from working in some software, including Qupzilla.

:)

**Comment by martinrotter** [comment]
#18 is relevant pull request.

**Comment by tomasko126** [comment]
Oh, thanks. I've already merged your PR into master! :)
