### ISSUE TITLE
novinky.cz adblock maže část textu článku

### ISSUE THREAD

**Issue by lukasojd** [tomasko126/easylistczechandslovak#177]
Adblock na novinky.cz maže kusy článků

viz screen https://screenshots.firefox.com/tKwCCMwivKN5qfmt/www.novinky.cz

https://www.novinky.cz/domaci/486012-cesi-rozhoduji-o-vetsine-v-senatu.html

ve chvíli kdy vypnu adblock text článku se zobrazí

**Comment by bogachenko** [comment]
I wrote here #181
