### ISSUE TITLE
Reklamy - zive.cz

### ISSUE THREAD

**Issue by 100petr** [tomasko126/easylistczechandslovak#179]
Web zive.cz a dalších co pod ně spadají mají nahoře, na levé a pravé straně reklamy. S těmito weby je problém asi často..

**Comment by petersaly** [comment]
https://github.com/tomasko126/easylistczechandslovak/pull/195

**Comment by petersaly** [comment]
@tomasko126 @Aslanex ako to tu funguje - kto zatvara issue?

**Comment by 100petr** [comment]
Vypadá to, že zive už je bez reklam, mohu poprosit ještě o blokaci na mobilmania.cz? Tam se zobrazují reklamy na eset, t-mobile aj.

**Comment by Hakatitla** [comment]
@100petr otestuj a zavri ak OK

**Comment by 100petr** [comment]
http://prntscr.com/ljs9lr http://prntscr.com/ljs9p2 http://prntscr.com/ljs9qu na zive vidím reklamu na t-mobile, czc, mall 
A na mobilmania se občas ukáže reklama na czc.

**Comment by 100petr** [comment]
Půjde s tím něco dělat? Protože to zive vypadá, jako by tam AdBlock skoro nechtěl fungovat, ale blokuje něco..  Nyní jsem narazil na problém, že s AdBlockem se mi nezobrazí video (minimálně u článku https://vtm.zive.cz/clanky/dobre-vedet-co-rikaji-slavne-keplerovy-zakony-o-pohybu-planet/sc-870-a-196066/default.aspx) po vypnutí se načte.
S: http://prntscr.com/llrbvz
Bez: http://prntscr.com/llrc6q

**Comment by Hakatitla** [comment]
Vzdy ked zablokujeme reklamy, zmenia na zive.cz nazvy a poziciu elementov, a potom nefunguju existujuce pravidla. Adblock funguje ako ma. Asi s tym nic neurobime ak tento ping pong bude pokracovat.

**Comment by 100petr** [comment]
Věřím, že si s tím snad nějak poradíte. Pokud to nepůjde, nedá se nic dělat. 
Zatím to uzavřu, když to vypadá takto beznadějně.

**Comment by 100petr** [comment]
Zjistil jsem, že s AdBlockem na zive se nechtějí zobrazit videa.

**Comment by Hakatitla** [comment]
@100petr 
Napis administratorom tohto repozitara aby zmergovali pull request https://github.com/tomasko126/easylistczechandslovak/pull/202 
s tym by to mohlo ist.
