### ISSUE TITLE
Novinky.cz

### ISSUE THREAD

**Issue by trumpeta** [tomasko126/easylistczechandslovak#181]
Ahoj, je to tu opět, Novinky jsou zaplevelené reklamou, czechlist poslední revizi mám nainstalovaný.
Každý týden tam přidávají nové věci, občas se to poadří vymazat kosmetickým filtrem, ale jde to obtížně protože všechny atributy elementů jsou randomizované. Bylo by potřeba aktualizovat. Pro ilustraci přikládám snímek stránky s aktivním uBlockem

![](https://i.imgur.com/IFx6Vmz.jpg)

**Comment by bogachenko** [comment]
The problem is in the cookies. Promotional cookies. You block them for this site = there will be no advertising.

I recommend uMatrix, it may seem difficult to learn, but it is not.
