### ISSUE TITLE
sme.sk anti adblock  

### ISSUE THREAD

**Issue by petersaly** [tomasko126/easylistczechandslovak#189]
![image](https://user-images.githubusercontent.com/7593516/47951413-a7cec300-df60-11e8-8db2-a0f6f754bd8a.png)

can by blocked by filtering url tinypass.com

**Comment by kukinko** [comment]
pull request https://github.com/tomasko126/easylistczechandslovak/pull/190

**Comment by rdev-software** [comment]
opat sa zobrazuje

**Comment by Hakatitla** [comment]
https://github.com/tomasko126/easylistczechandslovak/issues/260
