### ISSUE TITLE
emimino.cz

### ISSUE THREAD

**Issue by Hakatitla** [tomasko126/easylistczechandslovak#213]
![image](https://user-images.githubusercontent.com/7593516/50521642-f57e2c80-0ac6-11e9-9f68-4d95b448d661.png)

leftover place after cut ads

##.r-megaboard.r-box

**Comment by tomasko126** [comment]
Solved in https://github.com/tomasko126/easylistczechandslovak/commit/5d320b16f9fa19b1cbd0f3e5833520971004ea1c
