### ISSUE TITLE
Feature Request: Pi-hole compatible Blocklist

### ISSUE THREAD

**Issue by siskajakub** [tomasko126/easylistczechandslovak#214]
Hello,

Current blocklists are compatible with many adBlocking software but they cannot be used with [Pi-hole](https://pi-hole.net).

[Pi-hole](https://pi-hole.net) blocks ads on DNS level, therefore input blocklist needs to be slightly different. In short, it shall contain only domain names.

Would be it be possible to introduce a new blocklists dedicated for [Pi-hole](https://pi-hole.net) use?

Thank you

**Comment by addisr** [comment]
There are only few rules you could use to block at DNS level (all 1st party blocking rules not having any path specified - quickly looking through filters there are only about 10 of those). You can add them manually.

You can also try to use 3rd party blocking rules but this might break some sites.

I don't think there will be a dedicated pi-hole hosts file. You can try [this one](https://github.com/qxstyles/turris-hole-czech-block-list).
