### ISSUE TITLE
tv.sms.cz

### ISSUE THREAD

**Issue by Hakatitla** [tomasko126/easylistczechandslovak#215]
prazdne miesto po zablokovani reklami:

![image](https://user-images.githubusercontent.com/7593516/50640643-b851e880-0f65-11e9-9334-80483aede8b6.png)

navrh na skrytie elementu:
###P_reklama_horni

**Comment by vobruba-martin** [comment]
Po skryti toho elementu dojde k tomu, ze ta menu lista prekryva nahledu jednotlivych poradu.

**Comment by Hakatitla** [comment]
Takze sa to nemoze skryt.
Ja mam riadkove zobrazenie tam to nerobilo.
