### ISSUE TITLE
Nefunkční email na centrum.cz

### ISSUE THREAD

**Issue by lukasojs** [tomasko126/easylistczechandslovak#223]
Dobrý den, dneska mi přestal fungovat email na centrum.cz, na podpoře mi řekli, ať si vypnu adblock. Přitom reklamu na centrum.cz vidím, ale mail mi nefunguje. Když ho vypnu, tak to opravdu funguje. Může se na to někdo podívat? Děkuji

**Comment by teala12** [comment]
Koukal jsem na mail na centrum.cz a uz tam zadne problemy nenachazim, @lukasojs je i u vas vse ok?

**Comment by lukasojs** [comment]
Dobrý den, už je to ok. Děkuji
