### ISSUE TITLE
nova.cz filtr "Video nelze přehrát, protože máte aktivní AdBlock."

### ISSUE THREAD

**Issue by slrslr** [tomasko126/easylistczechandslovak#231]
V uBlock Origin 1.18.2 mám filtry třetích stran:

Regionální, jazykové (1/38)
CZE, SVK: EasyList Czech and Slovak​
​​​​1 590 použito z celkových 1 591​​​​

Když na list kliknu, zobrazuje se:

> [Adblock Plus 2.0]
> ! Homepage: http://adblock.sk
> ! Title: Easylist Czech and Slovak filter list
> ! Last change: 08/01/2019
> ! List maintainers: tomasko126, Aslanex, vobruba-martin, Moskoe, Fanboy
> ! GitHub repository: https://github.com/tomasko126/easylistczechandslovak

No a na stránce http://tn.nova.cz/clanek/prasknul-vam-displej-na-mobilu-opravte-si-ho-doma-navod.html je video které nefunguje, místo toho je text: "Video nelze přehrát, protože máte aktivní AdBlock."

**Comment by Aslanex** [comment]
Bohužel se Nova rozhodla nepřijímat návštěvníky používající Adblock. Obejít toto omezení je většinou nad naše kapacity, jedinou možností je tedy navštěvovat jiný web...

**Comment by kubalav** [comment]
Vyskúšaj v uBlock Origin: Možnosti - Moje pravidlá - Dočasné pravidlá
pridaj tento riadok:
tn.nova.cz doubleclick.net * allow

**Comment by slrslr** [comment]
> tn.nova.cz doubleclick.net * allow
Ne toto na tom nic nezměnilo. (otevřeno i v anon. okně)

**Comment by kubalav** [comment]
Neviem, mne to ide. Vyskúšané na Opere, Vivaldi. Nedal si náhodou toto pravidlo medzi Moje filtre? Skúste niekto overiť funkčnosť.
