### ISSUE TITLE
mojanitra.sk

### ISSUE THREAD

**Issue by Hakatitla** [tomasko126/easylistczechandslovak#239]
Add all over page. 

http://www.mojanitra.sk/subportals2/santana-music-bar-nitra-to-prave-uvolnenie-nitra.phtml?id_temy=812&action=clanky&id_clanku=143379

**Comment by tomasko126** [comment]
Fixed in https://github.com/tomasko126/easylistczechandslovak/commit/89bb9003e46274d4ecacedc3cc5a6841a6ec5a83
