### ISSUE TITLE
Reklamy idnes.cz

### ISSUE THREAD

**Issue by petrmobil** [tomasko126/easylistczechandslovak#241]
Zdravím, mohl by se někdo mrknout na reklamy, které se mi zobrazují na webu idnes?

Osobně používám vlastní filtry, které mi fungují. Tedy dávám k dispozici a jestli jsou ok, klidně použijte.

> idnes.cz##iframe[scrolling="no"]
> idnes.cz###widesquare
> idnes.cz###halfpagead
> idnes.cz###halfpagead_spodni
> idnes.cz###branding

**Comment by addisr** [comment]
Rád bych pomohl, ale žádné reklamy nevidím. Kde přesně je vidíš (link, screen) + případně jaký prohlížeč/adblocker (měl bys používat [uBlock Origin](https://github.com/gorhill/uBlock)).

**Comment by waclaw66** [comment]
iDNES nově nasadilo generované url, na které filtry neučinkují...

`<h1 class="packa">
						<a href="https://o.seznam.cz/ochrana-udaju/personalizovana-reklama/" target="_top">
							<img class="small" src="//www.idnes.cz/SEEZf8ZfcKR_Hxy21cnzeZZRFautxV_OGf/ILBqLfn3APkFjGJKnpNxdxgPxRASE" alt="Seznam.cz reklama" width="20" height="20">
							<img class="big" src="//www.idnes.cz/SEDZqX-GGB9ltabXVmZM1D4hxFH/lDnCGA3e7NDOF8PM6Zhqhpy4a8iGZ7oxSE" alt="Seznam.cz reklama" width="100" height="20">
						</a>
					</h1>`

**Comment by addisr** [comment]
Opět, hodilo by se info o jaký prohlížeč se jedná + link atd. Pro mě se pořád žádné reklamy nezobrazují.

**Comment by waclaw66** [comment]
Aha, sorry, chápu. Firefox 66b13 x64, uBlock Origin v1.18.4. Reklamy ze někdy zobrazí, jindy ne.
Zkoušel jsem také Firefox 67a1 s úplně stejným nastavením uBlocku, smazané cookies, bez přihlášení a žádná reklama. Stránka se generuje v každém jinak, v 66b13 je horní reklama v tabulce...
`<table id="d5d4df30f6dc532a335f53075d8be0aa5" class="r-main ahead s_branding" style="margin: auto;"><tbody>`
v 67a1
`<table id="r-leaderboardhp" class="r-main ahead s_branding">`
a je skryta pravidlem
`table[id*="leaderboard"]`

Zkusil jsem tedy v 66 nový profil, zobrazeno bez reklam s "r-leaderboardhp". Vypadá, že si nějak trackují prohlížeč a vybraným servírují nový "vylepšený" systém reklam s náhodnými identifikátory, jako to začalo dělat kdysi zive.cz.

**Comment by igregr** [comment]
Potvrzuji, screenshot treba zde: 
<img width="1425" alt="Screenshot 2019-03-14 at 00 32 18" src="https://user-images.githubusercontent.com/5960606/54321287-c02aaa80-45f0-11e9-8b1d-e665878d2834.png">  stránka se pak generuje např: `https://www.idnes.cz/FgHb8YHKq9zlhs_AzNMwc32xLJglsp_xUQ4jMydEbkQ/8am9xeCQ92ACSYAJjtDA0M88yMGY2z5YHZislN9sUFZ/hZaEAQWR9G5RfEGxQ0LVoQD8rhjQJ1FM_5ED/jv_4l-dXpZU7Fa5l2rHQnFUNSmmXm2boZgPfatLTpHn/4mJmC2sfHVHmNjmwVlDerzZV1RhVSXDfihi/_fZYljsvbXqVmtg8g4W3nWKh7WxCXaPfITuGJUi/dPCAPZfOanNxMUwR2kcnFZ4sT/Qxk-Zp5THQUxX237whXViTptxC-KmVyOs7XXgFg`

chrome Version 73.0.3683.75, ublock origin.
