### ISSUE TITLE
Zive video

### ISSUE THREAD

**Issue by 100petr** [tomasko126/easylistczechandslovak#250]
Na zive.cz při spuštění videa začne řvát reklama a obraz stojí. Přehraje to zvuk první reklamy, od které se zhruba 2 sekundy před koncem zobrazí i obraz, pak začne druhá u které se děje to samé. Dále ping-pong na webech jako zive, mobilmania s reklamy stále pokračuje. Prohlížeč Opera.

**Comment by addisr** [comment]
Nedaří se mi to nikde nasimulovat. Firefox i Chrome ok.

**Comment by 100petr** [comment]
Tak teď to jen dlouho načítá video, pak se zobrazí na dvě sekundy reklama, pak zase načítá a opět dvě sekundy reklama (obě již bez zvuku) znovu načítá a pak video. Nevím, jestli zkouší jak zobrazovat reklamy..

**Comment by 100petr** [comment]
https://youtu.be/FQbSr4eooXg povedlo se mi problém nahrát. Za text uprostřed videa se omlouvám, stáhl jsem něco bez vyzkoušení k zaznamenání problému.

**Comment by addisr** [comment]
Z videa to vypadá že nemáš žádný adblocker, máš to celkově plné reklam. 

Nainstaluj [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm), smaž/vypni jiný adblocker a ověř si že je povolený CZ/SK easylist. Pak by to mělo být ok.

**Comment by 100petr** [comment]
V danou chvíli jsem měl zapnutý základní Adblock z opery (viz ta modrá ikona u adresy). Zkusím zítra ten origin a dám vědět.Odesláno z mého chytrého telefonu Samsung Galaxy.
-------- Původní zpráva --------Od: addisr <notifications@github.com> Datum: 21.04.19  21:40  (GMT+01:00) Komu: tomasko126/easylistczechandslovak <easylistczechandslovak@noreply.github.com> Cc: 100petr <pitilonek@gmail.com>, Author <author@noreply.github.com> Předmět: Re: [tomasko126/easylistczechandslovak] Zive video (#250) Z videa to vypadá že nemáš žádný adblocker, máš to celkově plné reklam.

Nainstaluj uBlock Origin, smaž/vypni jiný adblocker a ověř si že je povolený CZ/SK easylist. Pak by to mělo být ok.



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tomasko126/easylistczechandslovak","title":"tomasko126/easylistczechandslovak","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/tomasko126/easylistczechandslovak"}},"updates":{"snippets":[{"icon":"PERSON","message":"@addisr in #250: Z videa to vypadá že nemáš žádný adblocker, máš to celkově plné reklam. \r\n\r\nNainstaluj [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm), smaž/vypni jiný adblocker a ověř si že je povolený CZ/SK easylist. Pak by to mělo být ok."}],"action":{"name":"View Issue","url":"https://github.com/tomasko126/easylistczechandslovak/issues/250#issuecomment-485277209"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/tomasko126/easylistczechandslovak/issues/250#issuecomment-485277209",

"url": "https://github.com/tomasko126/easylistczechandslovak/issues/250#issuecomment-485277209",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by 100petr** [comment]
Po nainstalování doplňku je zive pěkně čisté. Děkuji za pomoc.

ne 21. 4. 2019 v 21:43 odesílatel Petr Švrček <pitilonek@gmail.com> napsal:
