### ISSUE TITLE
idnes reklamy

### ISSUE THREAD

**Issue by 100petr** [tomasko126/easylistczechandslovak#251]
Na https://www.idnes.cz se zobrazují reklamy. Když jsem zablokoval dané bannery, zase se ukázala reklama po celém kraji stránky a už jsem se na individuální blokování vykašlal. Mám nainstalovaný uBlock Origin.

**Comment by addisr** [comment]
Bohužel já žádné nevidím takže teď asi nepomůžu. Možná to bude podobné jako minule (#241) kdy dělali rollout postupně a ne pro všechny najednou.

**Comment by 100petr** [comment]
http://prntscr.com/nkfjb2 - nahoře
http://prntscr.com/nkfjez - napravo 
http://prntscr.com/nkfjk9 - napravo
http://prntscr.com/nkfjru - napravo
http://prntscr.com/nkfjy7 - nahoře
http://prntscr.com/nkfkau - reklamy po stranách

**Comment by addisr** [comment]
Hm, měl jsem v testovacím prohlížeci jen staré filtry, takže nakonec opravdu nic nevidím. Můžeš zkusit smazat cookies pro idnes, uvidíš jestli to pomůže.

**Comment by 100petr** [comment]
Smazání cookies pro idnes pomohlo, už tam mám jen nějakou malou reklamu na máslo http://prntscr.com/nkfp2a 😀
