### ISSUE TITLE
vložené youtube video na pctuning.cz

### ISSUE THREAD

**Issue by kparal** [tomasko126/easylistczechandslovak#258]
Ahoj, pokud otevřu stránku
https://pctuning.tyden.cz/multimedia/hry-a-zabava/57081-vzestup-ciny-vyhra-globalizace-nad-zdravym-rozumem?start=3
a mám zapnutý `Easylist Czech and Slovak filter list` tak se mi nezobrazí youtube video v článku. Jakmile ten filtr vypnu, tak se zobrazí.

Není to reklama, video by se mělo zobrazovat vždy. Takže asi chyba v tomto filtru?

**Comment by addisr** [comment]
Diky za reporty, také fixnuto v 8a7b4df

**Comment by kparal** [comment]
Díky moc.
