### ISSUE TITLE
Skrytí obsahu na search.seznam.cz

### ISSUE THREAD

**Issue by BrianSLedoux** [tomasko126/easylistczechandslovak#261]
Pokud si zahledám 'auto' na search.seznam.cz, zmizí mi pod výsledkem 'Auto › Články.seznam.cz' všechny články

**Comment by BrianSLedoux** [comment]
Taktéž na dotaz 'zirafa' se skryje výsledek s obrázky.

**Comment by addisr** [comment]
Jaký adblocker/prohlížeč? Mě se to neděje.

**Comment by BrianSLedoux** [comment]
Adblock Plus 3.5.2
Chrome Version 75.0.3770.90 (Official Build) (64-bit)

https://snag.gy/cZ5b1s.jpg

**Comment by addisr** [comment]
Myslel jsem si to, bohužel tohle pravidlo není u nás ale [zde](https://github.com/abp-filters/abp-filters-anti-cv/commit/531daa3ce6f96304bbabc4135d66101ec819d3b7). Snažil jsem se jim to včera vysvětlit, ale jestli to opraví nevím.
