### ISSUE TITLE
mall.tv reklamy

### ISSUE THREAD

**Issue by Aslanex** [tomasko126/easylistczechandslovak#266]
https://www.mall.tv/gebrian-plus-minus/potrebuje-vic-pomoct-libensky-most-nebo-spis-jeho-okoli

Žádné blokování reklam ve videu.

**Comment by addisr** [comment]
U mě nic (Firefox/Chrome). Zkus promazat cookies pro doménu.

**Comment by Aslanex** [comment]
Už vidím, blokování funguje jen na Ublock Origin a ne na ABP.

**Comment by addisr** [comment]
Je to tak, ABP je pro dnešní internet nepoužitelný adblocker.
