### ISSUE TITLE
Zive.cz zobrazení

### ISSUE THREAD

**Issue by 100petr** [tomasko126/easylistczechandslovak#268]
Již od včerejška pozoruji špatné zobrazování zive.cz - http://prntscr.com/p2mysb
Zkoušel jsem vymazat cookies, obnovit výchozí nastavení uBlock Origin, ale web se zobrazuje stále špatně. Občas se stránka načte správně, ale jen málokdy. Při vypnutém uBlock Origin načítá vždy správně.

**Comment by addisr** [comment]
Aktualizuj si filtry + promaž ještě jednou cookies. V posledním commitu je opravené i zive a jde bez reklam.

**Comment by 100petr** [comment]
Vypadá, že to fugnuje. D9ky.
