### ISSUE TITLE
rajce.idnes.cz

### ISSUE THREAD

**Issue by marakoss** [tomasko126/easylistczechandslovak#27]
On 5.3.2016 you have added rule:

`+idnes.cz##A[class][href][style] ` 

which disables browsing a viewing photos (main use case) for web rajce.idnes.cz .

Remember that domain idnes.cz holds many subsites and you can't just apply this kind of rules globally.

--

Dne 5.3.2016 jste přidali pravidlo:

`+idnes.cz##A[class][href][style] ` 

které zněmožňuje procházení a prohlížení fotek (hlavní použití) webu rajce.idnes.cz.

Myslete na to, že doména idnes.cz má pod sebou několik samostatných webů a tak nemůžete aplikovat takovýto druh pravidel globálně.

**Comment by tomasko126** [comment]
@marakoss Thanks for spotting this issue. The problematic filter has been deleted, see 6eba2f197b47826050acf9340abb8542b9f2f5fa
