### ISSUE TITLE
novinky.cz

### ISSUE THREAD

**Issue by waclaw66** [tomasko126/easylistczechandslovak#270]
Novinky jsou rozbite. Po nacteni stranky, tato zmizi a zobrazi se pouze "500 - Error".

**Comment by addisr** [comment]
U mě bez problému.

**Comment by waclaw66** [comment]
Vyzkoušel jsem také Chrome a tam bez problému. Pak ještě čistý Firefox pouze s uBlock Origin, tam to pořád nefunguje. Po vypnutí "CZE, SVK: EasyList Czech and Slovak" je to ok. Zkusím přijít na to, který filtr to dělá.

**Comment by waclaw66** [comment]
Jedinej rozdil vyp/zap zdejsiho listu vidim v konzoli. Kdyz se objevi posledni chyba "this._getCanonicalParams is not a function", tak se zobrazi i ta hlaska 500...

![obrazek](https://user-images.githubusercontent.com/15554561/71206738-93a16e80-22a5-11ea-9f5a-2505fc291bd3.png)

**Comment by addisr** [comment]
Zkus přidat toto do filtrů, pomůže to? `novinky.cz##+js(aeld, error)`

**Comment by waclaw66** [comment]
Pomůže. Díky!

**Comment by addisr** [comment]
Nikdo jiný si zatím nestěžoval + extra pravidlo vypadá, že není potřeba. Zavírám.

**Comment by waclaw66** [comment]
Jo, už to funguje i bez filtru https://github.com/tomasko126/easylistczechandslovak/issues/270#issuecomment-567954196. Asi změna na novinkách.
