### ISSUE TITLE
oGame

### ISSUE THREAD

**Issue by Kattnienika** [tomasko126/easylistczechandslovak#276]
Při hraní webové hry oGame se zobrazuje v pravé části reklamní banner. Podařilo se ho skrýt níže uvedeným filtrem.

Filtr by se mohl přidat do místního filtru.

```
||gf2.geo.gfsrv.net/cdn43/*.jpg$image
```

**Comment by addisr** [comment]
Tento filtr by měl být spíš do globálního filtru než sem. Nejedná se o cz/sk stránku.
