### ISSUE TITLE
Yottlyscript.com - uz nevyuziva cookies tretich stran

### ISSUE THREAD

**Issue by VitekKalabek** [tomasko126/easylistczechandslovak#279]
Yottlyscript uz nevyuziva cookies tretich stran - bylo by prosim mozne odstranit nas z listu blokovanych?

**Comment by addisr** [comment]
Neni blokovane kvuli cookies, ale kvuli zobrazovani reklamy.

**Comment by VitekKalabek** [comment]
Tomu se ale musím bránit taky - není to reklama, ten skript vždycky zobrazuje jen výrobky z danýho shopu, na kterým uživatel je a snaží se vybírat alternativy/doplňky. Nikdy nic zvenčí.

**Comment by addisr** [comment]
Ok. Smazano.
