### ISSUE TITLE
mbank.cz

### ISSUE THREAD

**Issue by lkmb** [tomasko126/easylistczechandslovak#282]
Guys,
referring to this thread https://forums.lanik.us/viewtopic.php?f=64&t=44681 - is anybody able to help us fix the issue EasyList vs. mBank?

thanks in advance,
Lukas

**Comment by addisr** [comment]
We can help for sure. But it looks like it requires mbank account to reproduce your issue, which I do not have and you can't provide any (according to forum thread) so I'm really not sure what can I do.

**Comment by lkmb** [comment]
I am able to provide any help needed, except for the test account.
If you tell me what to do, I will test it on my personal one.

**Comment by addisr** [comment]
Let's try adding this rule to your filters.
`@@||online.mbank.cz/Adv/`

**Comment by lkmb** [comment]
Adding that rule to filters works like a magic and I am not experiencing problems described previously.
Let´s do the magic for our clients as well. What is needed do do from your side, and when can that be live?

**Comment by addisr** [comment]
Rule added.

**Comment by lkmb** [comment]
When can this be merged into the main branch and applied on production environment? 
I am not able to see the pull request anymore, so I assume it´s done?
If yes, then I am still able to reproduce the problems with access.
