### ISSUE TITLE
Pravidla pro všechny subdomény idnes.cz

### ISSUE THREAD

**Issue by marakoss** [tomasko126/easylistczechandslovak#29]
Prosil bych @Aslanex, aby po sobě opravil všechny commity, ve kterých aplikoval pravidla globálně pro doménu idnes.cz aniž by vzal vpotaz existenci ostatních webů pod touto doménou (např. rajce.idnes.cz) a způsobil tak zásadní problémy ve funkčnosti těchto webů.

Dle toho co jsem viděl by mělo stačit přidat "www." na začátek každého řádku týkajícího se pravidel pro webu idnes.cz (mají tam autoredirect na verzi s www. ).

Prosím informujte mě o nápravě.

Děkuji

**Comment by Aslanex** [comment]
Omlouvám se za tuto chybu. Bohužel to není tak jednoduché, protože idnes.cz obsahuje obrovské množství webů, na které platí stejné filtry (např. všechny kraje, jako vary.idnes.cz). Pokusil jsem se ty nejpodivnější filtry odebrat, nadále budu hledat řešení, jak se s idnes.cz vypořádat.

**Comment by Destroyer** [comment]
Ja mam idnes vyreseny takto

    ! idnes.cz
    ||idnes.cz$script,first-party
    @@||idnes.cz/js$script,first-party
    @@||idnes.cz/cms$script,first-party
    @@||servix.idnes.cz$script,first-party
    @@||data.idnes.cz$script,first-party
    @@||jizdnirady.idnes.cz$script,first-party
    @@||mapy.idnes.cz$script,first-party
ale nevim jestli funguji vsechny weby - nevim jak to dukladneji otestovat.

**Comment by Aslanex** [comment]
To vypadá dobře - jakže to funguje? :D Mám zkušenosti jen s CSS filtry.

**Comment by marakoss** [comment]
@aslanex: mě by tak do smíchu nebylo. Je třeba si uvědomit, že máte v ruce mocný nástroj a neodborným zásahem můžete jak připravit provozovatele blokovaného webu o zisk, ale i naštvát samotné uživatele vaší služby, kterým přestal fungovat jejich oblíbený web. Takže tady není v ničím zájmu aby adblock nedělal jen práci, na kterou byl určen.

**Comment by Destroyer** [comment]
``||idnes.cz$script,first-party``
tim blokuju vsechny skripty na domenach *idnes.cz, jelikoz spousta tech reklam ma URL napr. ``http://www.idnes.cz/mon-aah-cdg-fpaj-pcb-ljc-cjl-fgb-cbgc-php-ibhp-afp-npcldjao-edflhlg-nikcl-kde-obfi-mam-ednj-aiecmjc-bia-pmo-mojco-dbflmld-ijd-ame-kfg-hm-/kultura.aspx?c=A160327_153589_kultura_hgj`` coz je ve skutecnosti schovany skript reklamy, takze to blokuju hromadne a potom pouze whitelistuju skripty, ktere jsou pro beh idnesu dulezite ... jako foto.aspx resi fotogalerie, jizdnirady.idnes.cz tam je zas naseptavac ktery nemuzu blokovat a mapy taky nemuzou bez skriptu fungovat, ale vzdy je povolena uz pak jen dana poddomena / potrebny skript

pro nazornou ukazku je dobre naucit se s loggerem v ublocku, ten ukazuje ktere pravidlo bylo aplikovano na ktery soubor/element apod.

-----
jak jsem zminoval uz v mem predchozim prispevku, pochopitelne by bylo nejlepsi zablokovat jen cast, ktera tyhle odkazy pak vyvori na webu a zavola, jenze to se mi v ublocku nepovedlo rozebehat
ta problematicka cast vypada nejak takto
``(function(){var e=function(e,d,n){var t=function(e){try{for(var d=0;d<e.childNodes.length;d++){var n=e.childNodes[d].nodeName.toLowerCase();if('div'==n||'iframe'==n||'img'==n)return!0}}catch(t){return!0}return!1};if(!t(document.getElementById('bmone2t-'+e))){var a=document.getElementById('bmone2n-'+e);if(a){var l=document.createElement('div');l.id='e'+d,a.appendChild(l);var o=document.createElement('script');o.src=n,document.getElementsByTagName('body')[0].appendChild(o)}}};if (typeof(bmone2n)=='undefined') {e('--KOD--', '--KOD--', '--KOD--ODKAZU--');e('--KOD--', '--KOD--', '--KOD--ODKAZU---');}})();`` 

tahle teoreticky lepsi metoda ma ale hacek v tom, ze adblock plus samotny neumi inline skripty blokovat, takze by to slo vyuzit stejne jen v ublock originu
-----
@marakoss vas komentar prilis nechapu, kazdou ucinne zablokovanou reklamou prichazi provozovatel o zisk. Otazka problemu s webem je spis problem poskytovatelu, kteri detekuji blokatory reklam a blokuji tyto uzivatele a vydiraji je aby si blokator vypli nebo opustili web.

**Comment by marakoss** [comment]
@Destroyer: tato issue vznikla protože se opakoval incident, kdy některá adbloková pravidla blokovaly nejen reklamy na idnesu ale i bězné funkce webu - konkrétně u nás na rajce.idnes.cz neběžely komentáře a fotoeditor - ktery je hlavním zdrojem našich příjmů nikoli reklama! Reklamu u nás klidně blokujte - naopak vám klidně výjdeme vstříc a nastavíme reklamám určité třidy, které u nás můžete zablokovat, ale vaše činnost nesmí ohrožovat náš bussiness model.

**Comment by Destroyer** [comment]
@marakoss Ok, to chapu, ze stejne pojmenovani css trid muze pusobit problemy. 
Prave proto navrhuji reseni na zaklade URL a blokovani skriptu, ktere tuto reklamu vytvari. Napr. s mym resenim ted pro skripty na rajceti (min na hl. strance, nevim, jak je to na ostatnich) plati whitelist, diky pravidlu idnes.cz/js, do ktereho spadne i rajce. Takze bohate staci pokud budou skripty pro reklamu a pro vas web nejakym zpusobem oddelene napr. do jedne slozky a nejake css tridy se vubec nemusi resit. 
Krome toho reseni pres blokaci skriptu zpusobi i rychlejsi nacitani webu - nemusi se stahovat a ani zpracovavat blokovane js.

**Comment by marakoss** [comment]
@Destroyer: finální řešení nechám na vás. Stejnou "Složku" pro všechny skripty s reklamou vám ale zajistit nemohu, přotože se načítaji z externích zdrojů. Děkuji za pochopení.

**Comment by Destroyer** [comment]
Skripty s reklamou nemyslim, naopak skripty ktere jsou nezbytne pro beh webu. U tech bych rad aby byly v jedne slozce a daly se snadno whitelistnout.

**Comment by marakoss** [comment]
@Destroyer ani takto se to nedá říct. Většina našich skriptů je skutečně ve složce /js, ale máme zároveň nalinkované externí knihovny typu jquery a nějaké knihovny které jsou sdílené pro všechny weby pod idnesem zajištujicí třeba html5 přehrávač videí atp.

**Comment by Destroyer** [comment]
V tom pripade jedine dve veci, ktere by se musely otestovat na mem reseni jsou:
1. skripty mimo rajce.idnes.cz/js, ktere jsou na vasi domene
2. sdilene skripty idnes.cz
externi knihovny moje reseni vubec neresi, ty se nacitaji vsechny.

Oboji ale muzu jen tezko otestovat, musel bych projit naprosto vsechny stranky na idnesu a jeho poddomenach abych vedel, co se kde nacita. (pochopitelne to same ale plati pro cssko).

**Comment by marakoss** [comment]
Pokusím se k tomu přes týden udělat nějaký přehled.

**Comment by Aslanex** [comment]
@Destroyer Mám obavu, že tento whitelist nefunguje - např. na stránce
http://ekonomika.idnes.cz/foto.aspx?r=eko-doprava&foto1=SUJ61c701_polep_bus_celk.jpg
se nic nezobrazí. Ale zkusím se během několika dnů podrobně podívat na tento typ filtrů.

@marakoss Je potřeba si uvědomit, že dokud nezačal Idnes používat agresivní textovou reklamu, vše fungovalo v pořádku, takže tyto složité filtry jsou až následkem jeho boje s AdBlockem, kterému se musíme pochopitelně bránit. Může to pak mít omylem dopad i na jeho podweby jako Rajče, protože jsou prostě jeho součástí, a to také není naše vina. Pokud nesdílíte většinu šablon a ani bussiness model, jaký je tedy smysl, že máte stejnou doménu? Samozřejmě není naším cílem vám ubližovat, jen to všechno vychází z agresivního Idnes, kterého jste bohužel součástí.

Adblock Plus, jako jeden z největších adblock softwarů, navíc umožňuje whitelist webu, pokud má tzv. nerušivé reklamy. Díky tomu je možné dokonce reklamu zobrazovat, pokud je viditelně označená a neruší, a myslím, že by nebyl velký problém reklamu na Idnes takto uzpůsobit.

**Comment by marakoss** [comment]
@Aslanex Váš přístup k veci je scestný. Příšel jsem sem za vámi vyřešit problém, kdy váš systém nedělal co by měl a nabídnul se k pomoci. Opravdu jsem zde nepřišel rozpoutat diskuzi na téma proč ten či onen má takovou nebo makovou doménu a jak funguje náš bussiness model. Stejně tak by za vámi mohl přijit kterýkoli z vašich uživatelů a říct, že mu adblock rozbil jeho oblíbený web - ale to neudělají, protože většina si neuvědomí, že je to vaše chyba, ale řekne si, že provozovatel webu má nějakou poruchu. Natož aby si pak jeho oblíbený web dal do "whitelistu". 

Můžete mě odkázat na nějaký resource, jak se píší pravidla pro adblock? Chtěl bych se podívat na zoubek tomu, proč "nejdou" napsat pravidla tak, aby se týkaly jen konkrétní domény a ne jejich subdomén.

Děkuji

**Comment by Aslanex** [comment]
@marakoss Pokud uživatelův oblíbený web dělá nevhodné kroky proti Adblocku, je to v podstatě porucha na jeho straně, my se to snažíme řešit, ale nemyslím si, že zodpovědnost padá jen na nás. Idnes v tomto případě (dle mého názoru) dělá nevhodné kroky proti Adblocku a Rajče je jeho součástí. Ale jen jsem na to chtěl upozornit, problém se snažím řešit.

Whitelistem jsem myslel funkci zvanou "Acceptable Ads", která je ve výchozím nastavení Adblocku Plus zapnutá, není tedy ze strany uživatele potřeba žádná akce. Více zde: https://adblockplus.org/en/acceptable-ads

Základní popis filtrů je třeba tady https://adblockplus.org/filters .

**Comment by Destroyer** [comment]
@Aslanex problem je v tom, ze ja nejsem ten, kdo tenhle obsah blokuje, musis vypnout svuj easylist a pak to pobezi :) 
myslim ze je problem v ``ekonomika.idnes.cz###main > DIV:not(.m-bg-1):not(#foot2)``

**Comment by Aslanex** [comment]
@Destroyer Nojo, pravda, moje chyba... Nechceš napsat @tomasko126 , aby tě ti povolil přidávání filtrů? :)

**Comment by Destroyer** [comment]
Nemam zrovna moc casu mimo prazdnin a hlavne pokud se budu chtit aktivneji zapojit, bude lepsi to resit pres pull requesty, uz jen proto, ze ty jeste nekdo muze (treba ty) predtim otestovat. Pokud pushnu nejakou zmenu ktera neco rozbije tak to neni idealni, takze urcite je lepsi pull req. cesta :)

**Comment by Aslanex** [comment]
Ok, není problém. Zkusil jsem v posledním commitu použít navrhnutý whitelist, snad to bude fungovat v pořádku.

**Comment by okias** [comment]
||idnes.cz^$first-party,script mrví rajče s iframem, dá se s tím něco dělat?

**Comment by Destroyer** [comment]
nejaka konkretni ukazka?

**Comment by wwwcz** [comment]
Dobry den, bylo by mozne z whitelistu odstranit nasledujici radek?
@@||servix.idnes.cz$script,~third-party
pres domenu servix.idnes.cz se serviruji reklamy, prosel jsem subdomeny idnesu a nevypada to, ze by se ta subdomena pouzivala k servirovani regulerniho obsahu.
Dekuji

**Comment by Destroyer** [comment]
@wwwcz spatne jsi testoval, tu domenu jsem tam nedal rozhodne jentak... pri jejim zablokovani prestanou fungovat videa na idnesu

co jsem tak zbezne koukal tak nejlepsi je kompromis, whitelist upravit na format

`@@||servix.idnes.cz/media$script,first-party`

**Comment by Aslanex** [comment]
Ok, díky za otestování, opraveno.
