### ISSUE TITLE
Problém na stránce zive.cz Nefungující přepínač

### ISSUE THREAD

**Issue by jrdst** [tomasko126/easylistczechandslovak#302]
Dobrý den
Chtěl bych nahlásit problém který se týká stránky www.zive.cz
Pro Premium uživatele je zde možnost přepnout stránky pomocí přepínače do tmavého režimu
Pokud mám ale zapnutý váš filtr tak přepínač nereaguje
Kontaktoval jsem tedy administrátory zive.cz a dostal jsem odpověď že by pomohlo aby jste neblokovali tento řádek

zive.cz##+js(aost, $.cookie, inlineScript)

Můžete se tedy na to podívat ?
Děkuji

**Comment by jrdst** [comment]
Dobrý den
Mohu se zeptat proč byl tento post uzavřen ?
Problém totiž stále přetrvává
Vyčistit celou mezipaměť jsem zkoušel
Děkuji

**Comment by MarekLu** [comment]
Vypadá to na špatný odhad na naší straně (Živě), problém bude asi někde jinde než v tomto řádku. Musíme to prozkoumat, protože aktuálně tlačítko nefunguje, i když jsou úplně všechny filtry uBlocku deaktivované. Pomůže až vypnutí celého uBlocku na doméně. Zítra se na to s vývojáři podrobně podíváme.

**Comment by jrdst** [comment]
To je divné
Mě stačí když odškrtnu pouze filtr CZE, SVK: EasyList Czech and Slovak a vyčistím mezipaměť
Pak už vše funguje
Používám ale pouze tyto filtry
uBlock filters 
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
EasyList 
EasyPrivacy
Online Malicious URL Blocklist
Fanboy’s Annoyance
Peter Lowe’s Ad and tracking server list
A zmíněný CZE, SVK: EasyList Czech and Slovak s tím ale nefunguje zmíněný přepínač.

**Comment by MarekLu** [comment]
Problém byl v tom, že ve filtrech se sice odstranil řádek s $.cookie, který používáme, ale vyměnil se za layout.tracker, na kterém je tento přepínač také závislý. Nějak jsme to ale teď obešli, takže přepínání už funguje i s uBlockem.

Kdyby ale filtry blokovaly jen reklamu a nezasahovaly do funkčnosti webu, byli bychom radši :-(
