### ISSUE TITLE
aktuality.sk - Zdá sa, že máte vypnuté reklamy

### ISSUE THREAD

**Issue by roman-sc** [tomasko126/easylistczechandslovak#303]
Myslim, ze po tom ako som si pridal vas list v ublock origin som si mohol zablokovat reklamu na aktualitach. Dovtedy som videl hlasku o tom, ze mam vypnute reklamy. Dnes sa hlaska vratila. Zda sa, ze znova blokuju blokovac reklamy.
priklad:
https://www.aktuality.sk/clanok/842429/koronavirus-matovic-a-krajci-daju-sancu-sulikovi-svoj-semafor-dnes-nepredstavia/

**Comment by addisr** [comment]
U me se nic nezobrazi. Zkus promazat cookies.

**Comment by roman-sc** [comment]
Zaujimave. Dokonca netrebalo ani premazat cookies, ani urobit ziadne zmeny v ublocku. Iba som vypol ublock na aktuality a teraz som to po odpovedi v tomto threade skusil zapnut a uz sa nezobrazuje "Zdá sa, že máte vypnuté reklamy".
