### ISSUE TITLE
Idnes.cz zive.cz atd

### ISSUE THREAD

**Issue by mazmar** [tomasko126/easylistczechandslovak#308]
Ahoj, 

mate nekdo vazne problemy se zobrazovanim tehle webu? on nabehne web, a po par sekundach se cele CSS rozbije. 
pritom mi ale prijde ze reklamy jsou na tom webu i predtym nez se rozbije, a obcas jsou tam vsechny i ty na pozadi

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/597771/103338489-de3ff400-4a7e-11eb-8d74-0af18c5d01dd.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/597771/103338497-e5670200-4a7e-11eb-89a3-ff21baf7d934.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/597771/103338524-f748a500-4a7e-11eb-949d-52d8a35b8305.png">

**Comment by Palivec** [comment]
Ahoj, nemam problem, u me vse ok

**Comment by Nabla128k** [comment]
Ahoj, mě na Raspberry Pi 4, Raspbian OS, Chromium, ofiko instalace - začalo Idnes dělat "Page is not responding" (nebo jak je přesně ta hláška). Když vypnu uBlock Origin tak se to načte bez hlášky, i když to trvá. S uBlockem to prostě zůstane viset. Na jiných výkonnějších strojích to nedělá. Nepřišel jsem na to kde se to zadrhne, je toho tam moc.
Zapnout blokaci "large media" nepomůže. Mám standardní sadu filtrů po instalaci uBlock, nijak neupravenou a nenašel jsem jinou stránku kde by to dělalo....

**Comment by addisr** [comment]
Taky ok. Zkus jiný prohlížeč s uBlock Origin.

**Comment by thenhustey** [comment]
@mazmar 

U mě to způsoboval jiný doplněk (myslím, že to byl příliš agresivní Privacy Badger).
