### ISSUE TITLE
games.cz nefunkční obrázky

### ISSUE THREAD

**Issue by wwwcz** [tomasko126/easylistczechandslovak#31]
Dobrý den, chtěl bych nahlásit pravidlo které blokuje všecvhny obrázky na games.cz:
||games.tiscali.cz/$image,script,~third-party
![games](https://cloud.githubusercontent.com/assets/18326379/14653185/112792ce-0678-11e6-86c9-579d47e814eb.png)

**Comment by tomasko126** [comment]
@wwwcz Vyriešené commitom 3da2651711c8d3a2b47bfce9267ce00df9528c94.
