### ISSUE TITLE
Seznamzprávy 

### ISSUE THREAD

**Issue by 100petr** [tomasko126/easylistczechandslovak#314]
Na seznamzpravy.cz se zobrazují reklamy. Vždy na pravé straně u článku. 
![image](https://user-images.githubusercontent.com/29830635/112286551-b92cdd00-8c8b-11eb-8116-e0d84974bfe7.png) ![image](https://user-images.githubusercontent.com/29830635/112285680-ddd48500-8c8a-11eb-8744-ae99aa3e887c.png) ![image](https://user-images.githubusercontent.com/29830635/112285739-ec22a100-8c8a-11eb-8b2c-b39b4dcfad39.png) ![image](https://user-images.githubusercontent.com/29830635/112286062-386de100-8c8b-11eb-8d7b-af52a302dae6.png) ![image](https://user-images.githubusercontent.com/29830635/112286116-458ad000-8c8b-11eb-9ff1-6a44f41756e3.png) ![image](https://user-images.githubusercontent.com/29830635/112286167-52a7bf00-8c8b-11eb-93e9-8f983a8a9004.png) ![image](https://user-images.githubusercontent.com/29830635/112286265-6d7a3380-8c8b-11eb-8327-d3fa0675ab0d.png) ![image](https://user-images.githubusercontent.com/29830635/112286306-77039b80-8c8b-11eb-96d6-4fc5bc4c518a.png)
a hromada dalších

**Comment by r-flash** [comment]
V uBlocku mi zabralo pravidlo
```
seznamzpravy.cz##^script:has-text(adLeaderboard)
```
