### ISSUE TITLE
Recent change seems to have broken krimi-plzen.cz filters in uBlock

### ISSUE THREAD

**Issue by meesha7** [tomasko126/easylistczechandslovak#319]
I'm sorry for the issue title, not sure how to best describe this. [This commit (bee2bd0)](https://github.com/tomasko126/easylistczechandslovak/commit/bee2bd0dcae25c566756ab77014d880be453b687) seems to have broken the filters on krimi-plzen.cz. Instead of having specific filters for all the div classes to block, there's now a wildcard filter. For some reason, it doesn't work, when it comes from this list, **but** it works, when I copy that filter into *My filters*. Is there any reason for uBlock to work like that?

uBlock version: 1.35.2

**Comment by addisr** [comment]
Have you changed the rules before putting them into _My filters_? They updated their class names so rule `krimi-plzen.cz##[class*="partner"]` no longer works.

**Comment by meesha7** [comment]
Found the issue, from the PR description:
> The issue is that the actual class used on the site contains \x0d\x0b instead of the ascii a. Not sure if it's a typo or if it was intentional, but it was a fun bug to investigate.
:smile:

**Comment by meesha7** [comment]
To add to this: it explains why it works when copying the selector from uBlock's popup and not writing it manually.
