### ISSUE TITLE
Replace $object-subrequest with $object

### ISSUE THREAD

**Issue by mjethani** [tomasko126/easylistczechandslovak#327]
https://github.com/tomasko126/easylistczechandslovak/blob/e5bd529b2bef34e63de064c0254dbd326b6f59db/filters.txt#L18

Adblock Plus [no longer supports `$object-subrequest`](https://adblockplus.org/development-builds/removed-support-for-the-collapse-and-object-subrequest-filter-options).

**Comment by mjethani** [comment]
You can [lint your filters](https://github.com/mjethani/flint):

```
npm i -g flint-tool
flint filters.txt
```

**Comment by mjethani** [comment]
> You can [lint your filters](https://github.com/mjethani/flint)

There's one more error:

```
easylistczechslovak+easylist.txt:5536: ERROR: Domain -~localads.cab contains non-hostname character ~

/localads.$domain=-~localads.cab

```

**Comment by addisr** [comment]
Thanks. Second error is from EasyList and has been [fixed](https://github.com/easylist/easylist/commit/99fe19df0b503325f06a2750ba8be6747dbb4dee).
