### ISSUE TITLE
https://www.sport.cz/ ads

### ISSUE THREAD

**Issue by ryanbr** [tomasko126/easylistczechandslovak#329]
Hey, Ads on this site: (using mobile user agent)

`https://www.sport.cz/hokej/extraliga/clanek/2807797-kladensky-blackout-a-sokovany-kouc-komety-dvacet-lidi-z-bohnic-si-prijelo-zahrat-hokej.html#topstory` 

Have been trialing:  But still leaves some blank boxes.

```
sport.cz##[data-odoblakanova]
sport.cz##div[style^="visibility: visible; position: absolute;"]
sport.cz###site-page > .x12-be
sport.cz##.block-content > .x12-be
sport.cz##div[id*="Container"] > div[id*="Wrap"]
```
![sportcz](https://user-images.githubusercontent.com/1659004/137421312-32ac99f5-970d-42f0-8b68-0ff9b6d6497a.png)

**Comment by Tajnymag** [comment]
Can confirm addisr's test. I also can't reproduce the issue on my side.

@ryanbr, can you confirm the issue still persists?

**Comment by ryanbr** [comment]
Looks fine now, closing

**Comment by gorhill** [comment]
Unblocked ads have been reported, and I confirm they are present:

<details><summary>screenshot</summary>

![Screenshot from 2023-07-19 06-32-30](https://github.com/tomasko126/easylistczechandslovak/assets/585534/38500b07-bad3-4ff9-aa5c-892d8f8f16bd)

</details>
