### ISSUE TITLE
Issues on cas.sk 

### ISSUE THREAD

**Issue by edivaniadc** [tomasko126/easylistczechandslovak#331]
**Issue:** 
1 - Cookie consent message is blocked on https://www.cas.sk/
**Filter causing issues:**  
easylistczechslovak rule: `.etargetnet.` ( blocks SCRIPT: https://sk.search.etargetnet.com/gdpr/gdpr.js.php?ecmp=18 ) && EL rule: `||etargetnet.com^$third-party`and (blocks XMLHTTPREQUEST: https://sk.search.etargetnet.com/consent.php?findCookie=1&cookieName=euconsent-v2&_=
**Steps to reproduce:** manually disabling: `.etargetnet.` and then: `||etargetnet.com^$third-party` 
**Possible suggestion:** 
```
@@||sk.search.etargetnet.com/gdpr/gdpr.js.php?$domain=cas.sk
@@||sk.search.etargetnet.com/consent.php?findCookie=1&cookieName=euconsent-v2$domain=cas.sk
``` 
<img width="1242" alt="cas390" src="https://user-images.githubusercontent.com/57706597/138742700-1cf4180d-347b-4b31-90a2-07f1076ce9dd.png">
<img width="1278" alt="cas391" src="https://user-images.githubusercontent.com/57706597/138742705-48ec8d98-504e-496d-9696-b0d0223dbdd2.png">

2 - Block Pohodo widget below the article on: https://www.cas.sk/clanok/2601631/ostava-vo-vazbe-podnikatel-jozef-brhel-uz-pozna-rozhodnutie-sudu/
`cas.sk##div[data-api^="https://api.pohodo.sk/api/public/getWidgetProducts"]`
<img width="1357" alt="cas392" src="https://user-images.githubusercontent.com/57706597/138742925-9e5af4e7-fd31-44b2-8fed-54963f0c13c6.png">

3 - Block widget in the middle of the website) [class=pr-lg-20 pr-md-10](stable name) 
<img width="1248" alt="cas393" src="https://user-images.githubusercontent.com/57706597/138745430-e8c54dba-cbcc-4ff9-8a4e-afab2a0d48e2.png">

**Comment by edivaniadc** [comment]
Hello @addisr do you have by any chance any updates on this case please?
 Thank you so much.

**Comment by edivaniadc** [comment]
Hi @addisr just wondering if you had the chance to have a look at this case please?
Please let me know if you have any further questions.
Thank you so much.

**Comment by edivaniadc** [comment]
Hi @addisr, were you able to reproduce this case please?
Thank you so much.

**Comment by addisr** [comment]
I will look into blocking predpredaj.sk widget. Whitelisting etarget does not look like a good idea.

**Comment by edivaniadc** [comment]
> I will look into blocking predpredaj.sk widget. Whitelisting etarget does not look like a good idea.
Sounds good, thank you.

**Comment by edivaniadc** [comment]
Hi there @addisr Do you have any updates on this case please? (blocking predpredaj.sk widget)
Thank you in advance.
