### ISSUE TITLE
bottom ads on karaoketexty.cz

### ISSUE THREAD

**Issue by manuel-martinez-dev** [tomasko126/easylistczechandslovak#335]
### Issue:

Ads located after main content, just on top of footer.

![karaoke-ad](https://user-images.githubusercontent.com/40897997/142892143-96432958-167f-4587-a6f6-6fcfe3d4bf27.png)

### Example:

[website page](https://www.karaoketexty.cz/texty-pisni/imagine-dragons/my-life-1043369)

### Filter suggestion

karaoketexty.cz##div[id^="fluid_bottom"]

**Comment by addisr** [comment]
Not visible for me. Only few empty elements labeled as ads. Check your settings.

**Comment by manuel-martinez-dev** [comment]
Interesting, I tried with FF as well as on chrome and they apear after a force refresh; after a couple refreshes they seem to be empty placeholders.
