### ISSUE TITLE
Widget ads on cas.sk

### ISSUE THREAD

**Issue by edivaniadc** [tomasko126/easylistczechandslovak#338]
### Issue:
Block **Strossle** widgets labeled as **REKLAMA**.

### URL: 
https://www.cas.sk/clanok/2622831/slovensko-si-vysluzilo-kritiku-zo-strany-vyboru-osn-proti-muceniu-okamzita-reakcia-ministerstva/

### Possible filter: 
`cas.sk##a[href*="widgets.sprinklecontent.com"][target="_blank"]`

### Screenshots:
<img width="1130" alt="st" src="https://user-images.githubusercontent.com/57706597/146951643-11a81443-ff49-4d30-bb18-3f8b30967c9c.png">
<img width="1324" alt="stv" src="https://user-images.githubusercontent.com/57706597/146952730-02f58746-3f07-487b-81f5-34db22d53ee3.png">

**Comment by edivaniadc** [comment]
@addisr when you have the chance, could you please have a look at ^ issue please?
Thank you for your time.

**Comment by edivaniadc** [comment]
Any updates on this case please? Thanks

**Comment by edivaniadc** [comment]
Hi @addisr just wondering if you had the chance to have a look at this issue please?

**Comment by edivaniadc** [comment]
Hi @addisr just wondering if you had the chance to have a look at this issue please?

**Comment by addisr** [comment]
Not visible anymore.
