### ISSUE TITLE
Heureka .cz & .sk being completely inaccesible with NextDNS

### ISSUE THREAD

**Issue by itskemo** [tomasko126/easylistczechandslovak#345]
Would you take into consideration usage of the blocklist on NextDNS ? If so , just so you know it's currently blocking the access to both heureka.cz & heureka.sk which seems innapropriate.

**Comment by addisr** [comment]
Sounds like NextDNS issue no?

**Comment by itskemo** [comment]
Right, @addisr it seems like NextDNS is using the wildcard-domains format.
