### ISSUE TITLE
iDnes CSS blocked

### ISSUE THREAD

**Issue by redfoxcz** [tomasko126/easylistczechandslovak#348]
iDnes.cz CSS blocked

**Comment by redfoxcz** [comment]
Not yet fixed.
![idnes](https://user-images.githubusercontent.com/26900149/155206202-f991ac52-fffb-4aaa-bae8-119acc70bb01.png)

**Comment by addisr** [comment]
Make sure your filters are updated and clear cookies.

**Comment by s-p-c** [comment]
Works great, thank you!

**Comment by redfoxcz** [comment]
Still the same result as the image above. Opera GX 82.
Cookies cleared, filters updated. The only option is to disable the EasyList Czech.
