### ISSUE TITLE
anti adblock sport.idnes.cz

### ISSUE THREAD

**Issue by multibestia** [tomasko126/easylistczechandslovak#35]
na webu http://*.idnes.cz/ je nový anti adblock
Lze to nějak blokovat?

příklad: http://sport.idnes.cz

**Comment by multibestia** [comment]
asi to není úplně nejlepší ale zafunguje
|http://1gr.cz/*.js

**Comment by adawolfa** [comment]
@multibestia viz poslední komentář https://github.com/tomasko126/easylistczechandslovak/pull/34#issuecomment-223357855
Ten skript se schovává pod `*.png` a navíc na té doméně jsou asi nějaké důležité skripty nesouvisející s reklamou.

**Comment by vobruba-martin** [comment]
Predpokladam, ze tohle uz muzeme zavrit.
