### ISSUE TITLE
Gallery not working at zive.cz (Adblock Browser)

### ISSUE THREAD

**Issue by edivaniadc** [tomasko126/easylistczechandslovak#355]
**Issue:**
Rule from czech filter list seem to be preventing the gallery from loading and also from clicking on the right arrow (to go to the next page of the article).

**Sample URLs:**
1 - https://m.mobilmania.zive.cz/clanky/toto-jsou-nejocekavanejsi-smartphony-letosniho-roku-na-ktere-z-nich-se-vyplati-par-tydnu-ci-mesicu-pockat/sc-3-a-1354049#part=1

2 - https://m.zive.cz/clanky/cesky-grafik-upravil-svetoznama-loga-inteligentni-humor-funguje-i-v-mrazive-situaci/sc-3-a-215456

**Steps to reproduce:**
Android device
[Adblock browser](https://play.google.com/store/apps/details?id=org.adblockplus.browser)
Language list: cestina

**Filter that seem to be causing the issue:** 
`||cdn.cpex.cz^`

**Screenshot:**
![mobilmania](https://user-images.githubusercontent.com/57706597/160665114-88c0f808-4ec0-4940-996c-a33f7c5fd941.png)

**Filter suggestion:**
`@@||cdn.cpex.cz/cmp/*/cpex-cmp.min.js$domain=zive.cz`
`@@||cdn.cpex.cz/loader/*/settings/cnc/*_cz.js$domain=zive.cz`

_Allowing this rule doesn't load the **_reklama_** ads above the arrow. Unless ABP is disabled:_
<img width="667" alt="arrow" src="https://user-images.githubusercontent.com/57706597/160665175-104cb543-f3ae-45b7-8a75-2933a5130d8a.png">

_If English list is enabled these ads are also blocked by EL rule:`##.cnc-ads`__

**Comment by edivaniadc** [comment]
Hi @addisr when you have the chance can you please check if you can reproduce this case? thanks in advance.

**Comment by edivaniadc** [comment]
Hi @addisr did you have the chance to look into this case please? thanks for your time.

**Comment by edivaniadc** [comment]
Hi @addisr just wondering if have any updates or could reproduce this case please? Thank you in advance.

**Comment by addisr** [comment]
Working fine for me. Maybe some filter update already fixed it.
