### ISSUE TITLE
Pri prvni navsteve uBlock na firefoxu rozbije stranku

### ISSUE THREAD

**Issue by vybiral-tomas** [tomasko126/easylistczechandslovak#359]
Na sluzbach seznamu (seznam.cz, seznamzpravy.cz, ...) se pri prvni navsteve rozbije stranka (lze zreprodukovat v anonymnim okne). Po nacteni stranky se musi chvili pockat (obas to chce 1 refresh) a normalne se zobrazi popup s povolenim ukladani cookies a s uBlokem se nezobrazi nic.

Deje se to pouze na firefoxu (pravdepodobne kvuli `Total Cookie Protection`)

**Comment by addisr** [comment]
Nic podobneho se u me nedeje, zkus promazat cookie a vypnout ostatni rozsireni.
