### ISSUE TITLE
mall.tv

### ISSUE THREAD

**Issue by sugarfreesweetener** [tomasko126/easylistczechandslovak#363]
https://github.com/uBlockOrigin/uAssets/issues/14788

`endless-live.cz#@##reklama`

**Comment by addisr** [comment]
https://github.com/uBlockOrigin/uAssets/commit/4320c0458ad607201e7b7d79e89638601b1db1d3

**Comment by sugarfreesweetener** [comment]
if regional lists address stuff on regional sites, filters for addressed sites, if there are any, may be removed
