### ISSUE TITLE
seznamzpravy.cz

### ISSUE THREAD

**Issue by dportvine** [tomasko126/easylistczechandslovak#367]
`https://www.seznamzpravy.cz/clanek/ukrajinski-novyny-mi-boremosia-za-kozhnogo-z-vas-zaiaviv-u-prazi-mer-kiieva-vitalii-klichko-215452`

<details>
<summary>Screen</summary>

![2022-09-27_181004](https://user-images.githubusercontent.com/111344219/192565251-b11f46cf-cc09-4789-801c-d65e399b4521.png)
![2022-09-27_181033](https://user-images.githubusercontent.com/111344219/192565275-3622695b-6ea5-4e66-987b-09b468ca467e.png)
![2022-09-27_181131](https://user-images.githubusercontent.com/111344219/192565295-acd5c0b1-32d6-4fa3-bfb4-800c5e3724ef.png)
![2022-09-27_181147](https://user-images.githubusercontent.com/111344219/192565316-b5afb080-87e5-44c1-87ea-8fa7f5cd53ed.png)
</details>

<details>

```yaml
uBlock Origin: 1.44.4
Chromium: 105
filterset (summary): 
  network: 100863
  cosmetic: 126478
  scriptlet: 24265
  html: 0
listset (total-discarded, last updated): 
  removed: 
    plowe-0: null
    urlhaus-1: null
  added: 
    https://easylist-downloads.adblockplus.org/bitblock.txt: 31413-27, 3h.23m
    https://easylist-downloads.adblockplus.org/cntblock.txt: 1513-24, 3h.23m
    CZE-0: 724-0, 2m
    fanboy-cookiemonster: 41128-287, 3h.23m
    ublock-annoyances: 4835-52, 3h.23m
  default: 
    user-filters: 15-0, never
    RUS-0: 42229-147, 3h.23m
    easylist: 62213-88, 3h.23m
    easyprivacy: 30636-1574, 3h.23m
    ublock-abuse: 76-1, 3h.23m
    ublock-badware: 4190-103, 3h.23m
    ublock-filters: 32943-174, 3h.23m
    ublock-privacy: 249-8, 3h.23m
    ublock-quick-fixes: 216-10, 3h.23m
    ublock-unbreak: 1859-45, 3h.23m
filterset (user): [array of 19 redacted]
modifiedUserSettings: 
  advancedUserEnabled: true
  contextMenuEnabled: false
  showIconBadge: false
modifiedHiddenSettings: 
  filterAuthorMode: true
  popupFontSize: 13px
  popupPanelHeightMode: 1
supportStats: 
  allReadyAfter: 780 ms (selfie)
  maxAssetCacheWait: 847 ms
```
</details>

https://github.com/uBlockOrigin/uAssets/issues/15060

**Comment by staticf0x** [comment]
Maybe check for the `data-adtrackingtemporaryurl` attr, seems to be common for all these ads

**Comment by dportvine** [comment]
@tomasko126 
Up!
`https://www.seznamzpravy.cz/clanek/ukrajinski-novyny-praga-kazhe-pereselentsiam-stop-i-tim-khto-znakhodit-zhitlo-samostiino-225333`

**Comment by mapx-** [comment]
I get no ad @dportvine
