### ISSUE TITLE
Blokovat upozornění na Adblock?

### ISSUE THREAD

**Issue by Aslanex** [tomasko126/easylistczechandslovak#37]
Některé weby reagují na Adblock tím, že tam zobrazí okénko s prosbou o vypnutí. Má se to také blokovat, nebo pokud neblokuje přístup k webu, se to považuje za fér přístup a může se nechat?

**Comment by adawolfa** [comment]
Osobně mi vadí, když o vypnutí AdBlocku žádá web, který je opravdu neúnosně přecpaný reklamou. Na druhou stranu:

> Anti-Adblock should only be challenged if the system limits website functionality or causes significant disruption to browsing ([easylist.github.io](https://easylist.github.io/2013/05/10/anti-adblock-guide-for-site-admins.html)).

Vzhledem k tomu, že tento repozitář patří pod EasyList, tak by to asi respektovat nejspíš měl. Možná by se daly filtry proti popupům vyčlenit do samostatného repozitáře, nebo větve, ale to je nejspíš nápad vhodný jenom pro těch pár nadšenců.

**Comment by tomasko126** [comment]
@Aslanex @adawolfa 
Okno s prosbou o vypnutie AdBlocku by sa nemalo blokovať, ak okno nie je rušivé a neblokuje prístup ku stránke a jej obsahu. Vždy by sa malo prihliadať na [pravidlá](https://easylist.github.io/2013/05/10/anti-adblock-guide-for-site-admins.html) Easylistu, ako @adawolfa popísal vyššie.

**Comment by Aslanex** [comment]
Ok, díky za info.
