### ISSUE TITLE
filtr pro livesport.cz a evysledky.com

### ISSUE THREAD

**Issue by gugatr0n1c** [tomasko126/easylistczechandslovak#38]
Prosim pridat filtry pro

www.livesport.cz - ceska verze
www.evysledky.com - slovenska verze

Dost toho je na homepage, ale pak i v jednotlivych zapasech (klik na jakykoliv zapas a pak v tom popUpu).

diky

**Comment by adawolfa** [comment]
O tyhle reklamy se postará výchozí [globální EasyList](https://easylist.github.io/easylist/easylist.txt). V uBlocku tam žádné reklamy s tímto filtrem nemám.

**Comment by Aslanex** [comment]
Tyto stránky by už skutečně měly být blokované. Zkontrolujte si prosím nastavení filtrů.
