### ISSUE TITLE
zive.cz, mobilmania.cz tvrdsi blokovani

### ISSUE THREAD

**Issue by krejmaj** [tomasko126/easylistczechandslovak#41]
jelikoz zive a mobilmania uz vypada jakoby adblock nefungoval, je cas pritvrdit (blokuji jak tracking tak reklamy)

```
! zive.cz
! scripts
||zive.cz$script,first-party
||assets.adobedtm.com$script,domain=zive.cz
! whitelist
@@||zive.cz/Client.Scripts$script,first-party
@@||zive.cz/Client.Gallery$script,first-party
@@||zive.cz/_rev2015/js$script,first-party
@@||zive.cz/WebResource.axd$script,first-party
@@||zive.cz/ScriptResource.axd$script,first-party
@@||forum.zive.cz/styles$script,first-party
@@||speedtest2.zive.cz/js/script.js$script

! css filter
||zive.cz/_rev2015/css/layout-branding.css$stylesheet,first-party


! mobilmania.cz
! scripts
||mobilmania.cz$script,first-party
||assets.adobedtm.com$script,domain=mobilmania.cz
! whitelist
@@||mobilmania.cz/Client.Scripts$script,first-party
@@||mobilmania.cz/Client.Gallery$script,first-party
@@||mobilmania.cz/_rev2015/js$script,first-party
@@||mobilmania.cz/WebResource.axd$script,first-party
@@||mobilmania.cz/ScriptResource.axd$script,first-party
@@||forum.mobilmania.cz/styles$script,first-party
! css filter
||mobilmania.cz/_rev2015/css/layout-branding.css$stylesheet,first-party

! optional - vyhodi header a footer
||prolink.ostium.cz/5.0/$script

```

**Comment by Aslanex** [comment]
Opravdu je to tak hrozné? Přidal jsem pár jednoduchých filtrů na skrytí reklamy nahoře a vpravo a zive.cz už mi přijde čisté.

**Comment by krejmaj** [comment]
Aktualizoval jsem filtr, vypnul ten svuj a cisty mi to moc neprijde
![image](https://cloud.githubusercontent.com/assets/21038496/17701752/57e253e2-63cb-11e6-829c-487e232799e0.png)

navic jak rikam blokuji daleko vice nez jen kosmetickou reklamu - staci se podivat do vypisu z loggeru jaky skripty zive a mobilmania stahuje na pozadi

**Comment by Aslanex** [comment]
Ok, na tuto reklamu jsem předtím nenarazil. V zásadě je tento způsob blokování nebezpečný, protože může jednoduše znefunkčnit celý web, navíc není úkolem EasyListu blokovat všechny zbytečné serverové požadavky, ale jen reklamu.

Každopádně, když se vůči nám Živě.cz chová zle, není jiná možnost. Přidal jsem filtry do seznamu.

**Comment by krejmaj** [comment]
chtel bych pogratulovat zive za to, jak rychle prisli s vylepsenim
zatim nevim, jak tohle pravidlo napsat pro adblock, ale pro lidi co muzou cist tenhle topic tohle jim muze poradit jak to vyresit mimo adblock


```javascript
new function(g, d) {
    function p(a) {
        try {
            a.remove()
        } catch (c) {
            a.parentElement.removeChild(a)
        }
    }

    function u() {
        var a = d.createElement("script");
        a.onerror = function(c) {
            e.log("err", this.src, c);
            q(this.src) || (h = 1, e.log("adb bb"));
            p(a)
        };
        a.onload = function(c) {
            e.log("ok", this.src);
            q(this.src) || (h = 0);
            p(a)
        };
        a.src = k.lo("//GO.bbelEm") + k.lo("ents.coM") + k.lo("/pleasE/code");
        d.body.appendChild(a)
    }

    function q(a) {
        var c = "/" == a[0] || -1 < a.indexOf(window.location.hostname);
        e.log("local", a, c);
        return c
    }

    function m() {
        return Math.random().toString(36).replace(/[^a-z]+/g,
            "")
    }

    function l(a, c, b) {
        d.cookie = a + "=" + c + "; expires=Thu, 01 Jan " + b + " 00:00:00 UTC; path=/"
    }

    function n(a) {
        return !a || 0 == a.innerHTML.length || 0 === a.clientHeight ? (e.log("adb elem", a.id, a.className), h = 1) : 0
    }

    function r(a, c) {
        var b = d.createElement("div");
        b.innerHTML = "&nbsp;";
        a && (b.id = a);
        c && (b.className = c);
        d.body.appendChild(b);
        var e = n(b);
        b.parentNode.removeChild(b);
        return e
    }

    function v() {
        var a = d.getElementById(s);
        w.forEach(function(b) {
            b = g.atob(b);
            a.className = b;
            r(null, b);
            n(a)
        });
        x.forEach(function(b) {
            b = g.atob(b);
            a.id = b;
            r(b);
            n(a)
        });
        var c = d.getElementById(t);
        c.parentNode.removeChild(c)
    }

    function y() {
        if (h) {
            e.log("Adb on");
            l("adb", 1, 2025);
            var a = Math.floor(1E7 * Math.random() + 1);
            l("adb.key", a, 2025);
            e.log("Adb key", a)
        } else e.log("Adb off"), l("adb", 0, 2005), l("adb.key", 0, 2005)
    }
    this.version = "0.0.192";
    var k = this,
        h = 0,
        z = g.setTimeout,
        f = function() {},
        e = -1 < d.cookie.indexOf("ts.debug=1") && g.console || {
            log: f,
            error: f,
            warn: f,
            info: f,
            debug: f
        },
        x = "YmFubmVy cmVrbGFtYQ== c2tsaWs= cmVrbGFteQ== YmJ0aXRsZQ== cHJvbW8tYm94 c2tsaWtSZWtsYW1h".split(" "),
        w = "YWZzX2Fkcw== c2tsaWstYWRz c2tsaWstYWQ= c2tsaWs= cmVrbGFtYQ== YmJ0aXRsZQ==".split(" "),
        f = m(),
        s = "advert-" + f,
        t = "advert-link-" + f;
    k.lo = function(a) {
        return a.toLowerCase()
    };
    z(function() {
        var a = d.createElement("div");
        a.innerHTML = '<a href="//' + m() + ".performax.cz/abc/?utm_campaign=" + m() + '" id="' + t + '"><div class="afs_ads" id="' + s + '" style="position:absolute;">&nbsp;</div></a>';
        d.body.appendChild(a);
        v();
        h || u();
        g.addEventListener("beforeunload", y)
    }, 300)
}(window, document);

```

**Comment by Aslanex** [comment]
Tak to je hloupé, lepší filtry nevymyslím...

**Comment by Aslanex** [comment]
Dá se použít teda hodně riskantní věci jako `zive.cz###mainFORM > DIV:not(.cs-cnt-wrapper)`, ale docela se bojím to používat.

**Comment by krejmaj** [comment]
Byl jsem mimo internet nejakou dobu a koukam, ze nejake zmeny byly provedeny. Bohuzel nejsou idealni. 
https://github.com/tomasko126/easylistczechandslovak/commit/f501170cf0be39b913a620fb1e7824d416620af5 schova ikony jako logo, prihlasovaci ikonu apod. 
![image](https://cloud.githubusercontent.com/assets/21038496/18062170/f786d508-6e25-11e6-887e-c399fb14a29b.png)

Zive bohuzel zneuziva neschopnosti adblocku, ktery neumi blokovat inline skripty. Dokud se toto adblock nenauci, nebude mozne se ucinne branit.

**Comment by Aslanex** [comment]
Nene, ten filtr je definovaný takto: ` ||zive.cz/*/|$image,~third-party` , mělo by to tedy blokovat jen obrázky s adresou, která končí lomítkem.

Četl jsem o blokování inline skriptů a problém je, že by to šlo velice jednoduše obejít – skript by se přidal do nějaké funkce, která je pro funkčnost webu nutná. Ublock to prý umí, ale ABP to z tohoto důvodu umožňovat nechce.

**Comment by krejmaj** [comment]
Omlouvam se, | jsem prehledl. V tom pripade je to bug ublock originu, ktery toto pravidlo spatne zpracovava. 
![image](https://cloud.githubusercontent.com/assets/21038496/18088135/2aa59f62-6eb9-11e6-8a12-60342fb30655.png)
Kazdopadne ani tak mi neni poradne jasne, ktere pozadavky tedy chcete blokovat, obrazky koncicich na / jsem si v logu nevsiml.

**Comment by Aslanex** [comment]
Takto by se měly blokovat reklamy na pozadí, které mají náhodně generovaný název.

**Comment by novjan** [comment]
Ahoj.
Na reklamy jako tyto asi stále řešení přes ublock není, že?
![asd](https://cloud.githubusercontent.com/assets/22574170/19020553/7a25398c-88ac-11e6-91ed-43dc93af1cc9.jpg)

PS: Přihodíš prosím toto?
```
f1sport.auto.cz###page-header > .bx-leaderboard.bx-bb
f1sport.auto.cz###mainFORM > .bx-billboard.bx-bb
```

**Comment by Aslanex** [comment]
Ale jasně, že to nějak jde. Problém, je, že když autoři webu pořád mění jeho kód, tak potom taky chvíli trvá, než to změníme na naší straně. Živě.cz průběžně aktualizuji, o Autorevue jsem nevěděl, ale mělo by to teď být také v pořádku.

Celkově je vhodné tyto weby nenavštěvovat, když jsou tak ošklivé.

**Comment by novjan** [comment]
@Aslanex Ahoj. V mobilní verzi, když mají kapitoly, se objevil problém. Neozobrazuje se obsah, jelikož je zablokovaný potřebný js.
http://m.zive.cz/12-tipu-pro-mapycz-pouzivejte-je-jako-profik/a-184694#part=1

**Comment by Aslanex** [comment]
Opraveno, díky za upozornění.

**Comment by grezom** [comment]
http://m.zive.cz/12-tipu-pro-mapycz-pouzivejte-je-jako-profik/a-184694#part=1
Tento preklikavac kapitol je po aplikacii pravidiel vyssie nefunkcny. Da sa to fixnut?

**Comment by tomasko126** [comment]
@grezom @novjan Zdá sa, že sa tento problém už nevyskytuje, môžete potvrdiť?

**Comment by novjan** [comment]
@tomasko126 Už je to ok. :)
