### ISSUE TITLE
Add tasks to templates

### ISSUE THREAD

**Issue by inson1** [tomasko126/easylistczechandslovak#415]
1. Did you check the issues, if someone else didn't already open the issue?
2. Did you also check the closed issues?

**Comment by mlnrDev** [comment]
I already feel like templates are annoying for many people, having them check things like that when there isn't a lot of activity in the repo feels rather pointless.

**Comment by inson1** [comment]
sorry for spam, just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
