### ISSUE TITLE
zive.cz Advertising banner that cannot be closed

### ISSUE THREAD

**Issue by 3hryhik** [tomasko126/easylistczechandslovak#417]
### The filter you are reporting

On the website [www.zive.cz](url) there is an advertising banner that cannot be closed and urges you to turn off uBlock or pay the subscription fee. Previously this filter blocked this banner without any problems.

### The issue

The filter is not effective anymore

### Pages where this issue appears

www.zive.cz

### Screenshots/videos

![zive](https://github.com/tomasko126/easylistczechandslovak/assets/85852094/81e64c48-1f40-4fa8-aa13-1961e2771425)

**Comment by mlnrDev** [comment]
hi, I recommend using uBlock Origin and turning on the "AdGuard - Ads" filterlist, as it already blocks this popup.
