### ISSUE TITLE
Přehrajto.cz ad banner

### ISSUE THREAD

**Issue by KAJIKK** [tomasko126/easylistczechandslovak#418]
### Description

skrytí postranních bannerů a vrchního banneru
prehrajto.cz##a[href*="zalohuj.si"]

Taky jsem zkoušel je úplně odstranit (zmenšit prázdné místo), ale bohužel mi to funguje jen někdy:
prehrajto.cz##.grid-container:style(padding-right: 1.25rem !important; padding-left: 1.25rem !important; max-width: 90% !important; margin-left: auto !important; margin-right: auto !important;)

### Pages where these elements appear

prehrajto.cz

**Comment by mlnrDev** [comment]
zdravim, tieto filtre by mali postacit:
```
prehrajto.cz##.ad-leaderboard-alt-wrapper
prehrajto.cz###ad-leaderboard-alt-sides
prehrajto.cz##.content:style(margin-top: 0px !important;)
```

prosim skus ich a napis, ci to je v pohode, kedze obsah stranky je ocividne za registraciou a registrovat sa urcite nebudem :-)

**Comment by KAJIKK** [comment]
Vrchní banner už se neobjevuje, postranní bannery zanechaly prázdné místo. Nejlepší by bylo kdyby se dal <div class="page"> roztáhnout na celou stránku aby bylo vidět více videí najednou. Stránka je sice dotěrná ale registraci nevyžaduje. Zkouším na:
https://prehrajto.cz/hledej/breaking%20bad%20S01E01

**Comment by mlnrDev** [comment]
neviem, ci je v zaujme nasich filtrov "redesignovat" stranky ak su elementy a zostatky po nich odstranene. pridam ale filtre, ktore som postol vyssie
