### ISSUE TITLE
Přidání webu games.tiscali.cz

### ISSUE THREAD

**Issue by gizellos** [tomasko126/easylistczechandslovak#43]
Dobrý den,
nemohli byste prosím přidat filtr pro blokování reklam na webu [http://games.tiscali.cz/](http://games.tiscali.cz/)? Je tam toho vcelku dost.

**Comment by Aslanex** [comment]
Dobrý den,
bohužel, tento web používá neskutečně složitou metodu, aby se Adblocku vyhnul, takže není v našich schopnostech ho zablokovat. Maximálně můžu doporučit web vůbec nenavštěvovat.

**Comment by gizellos** [comment]
Děkuji moc za odpověď. Tak to se nedá nic dělat. Kdyby adblock nefungoval v 99% případů, tak bych to tam asi přežil, ale jak jsem zhýčkaný, tak je toho tam na mě prostě moc. :(

Ještě jednou díky za odpověď i za práci na tomto filtru. Na shledanou.

**Comment by Destroyer** [comment]
@gizellos zkuste zakazat cookies pro danou domenu, pokud se na ni neprihlasujete, nebudete je potrebovat

**Comment by iloveitalready** [comment]
Přidejte si tyto tři řádky do vašich filtrů:

games.tiscali.cz##script:inject(abort-on-property-write.js, bmone2n)
games.tiscali.cz###header:xpath(preceding-sibling::div)
games.tiscali.cz##:xpath(//comment()[contains(.,"iBILLBOARD")]/parent::*)

Zřejmě před rokem používali nějakou složitější metodu?

**Comment by Aslanex** [comment]
To jsou docela zvláštní filtry a na mém ABP nefungují, odkud je berete?

**Comment by Destroyer** [comment]
Adblock Plus je v blokování poměrně neschopný - tohle zvládá jen ublock origin. 
https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#procedural-cosmetic-filters

**Comment by Aslanex** [comment]
Aha. Vzhledem k tomu, že v ABP tyto nestandardní filtry nic nekazí, přidávám je do seznamu alespoň pro Ublock Origin.

**Comment by iloveitalready** [comment]
Požádal jsem o ně na Redditu a někdo je tam napsal.

**Comment by subrton** [comment]
Aktualizace pro uBlock Origin:
```
games.tiscali.cz##body:style(background: #000 !important)
games.tiscali.cz##:xpath(//comment()[contains(.,"iBILLB0ARD") or contains(.,"iBILLBOARD") or contains(.,"bbelements.com")]/parent::*) 
```

**Comment by Aslanex** [comment]
Aktualizováno, díky.
