### ISSUE TITLE
ad on online radio www.impuls.cz

### ISSUE THREAD

**Issue by wowfilip999** [tomasko126/easylistczechandslovak#440]
### The filter you are reporting

 https://github.com/tomasko126/easylistczechandslovak

### The issue

The filter is not effective anymore

### Description

can be fixed by add in filter this:
www.impuls.cz##.show.ads-popup

### Pages where this issue appears

https://www.impuls.cz/prehravac

### Screenshots/videos

this can be fixed by add cosmetic filter as i say in description
![obrazek](https://github.com/tomasko126/easylistczechandslovak/assets/67916726/6b48bfa9-c44a-423e-9566-39a40fc7e6c8)

**Comment by KarelCemus** [comment]
I see the same at https://radia.cz/radia/hitradio-city-praha and my filters are up to date.
