### ISSUE TITLE
zive.cz

### ISSUE THREAD

**Issue by FilipNovy** [tomasko126/easylistczechandslovak#45]
Ahoj.
Na zive.cz blokujete i nereklamíní obrázky, jako logo webu, odkaz na forum, ikony fora (http://forum.zive.cz/) .....
Prosím o opravu :)

**Comment by Aslanex** [comment]
Tato chyba se projevuje myslím jen v uBlocku, který špatně interpretuje filtry. Je to problém jen na fóru, nebo na celém webu?

**Comment by FilipNovy** [comment]
Na foru to blokuje všechny ikony fora (nové příspěvky atd.)
Na zive.cz schází např. logo.

Jinak ano mám ublock. Zatím vypadá, že ze všech možností funguje nejlépe.

**Comment by Aslanex** [comment]
Příslušný filtr jsem odstranil, snad se nebude po jeho odstranění zobrazovat reklama.
