### ISSUE TITLE
zive.cz

### ISSUE THREAD

**Issue by SMed79** [tomasko126/easylistczechandslovak#53]
Hi, 

```
||zive.cz^*/|$script
zive.cz##.bx-leaderboard
```
`http://www.zive.cz/`
https://adblockplus.org/forum/viewtopic.php?f=1&t=49868

**Comment by SMed79** [comment]
```
/\.zive\.cz/.*?\w{45,}/$script
zive.cz##.bx-leaderboard
```
https://adblockplus.org/forum/viewtopic.php?f=4&t=49997

**Comment by Aslanex** [comment]
Hi, this filter seems to block jQuery on zive.cz.

**Comment by tomasko126** [comment]
@SMed79 @Aslanex All ads should be blocked now - b41e211dc07f6c5501a65b313a7818743dbed340.
