### ISSUE TITLE
Aktualne.cz

### ISSUE THREAD

**Issue by Goues** [tomasko126/easylistczechandslovak#56]
Zdravím,

na webu Aktuálně.cz mají občas nějaké infografiky k aktuálním tématům. AdBlock mi kromě reklam blokuje i jejich obsah: [ukázka](https://zpravy.aktualne.cz/domaci/grafika-poslanci-koureni/r~7ff8feccbd1611e6bc740025900fea04/)

**Comment by Dukecz** [comment]
Blokováno filtrem `/viewid=*/site=*/size=` v EasyListu
