### ISSUE TITLE
lichess.org

### ISSUE THREAD

**Issue by ghost** [tomasko126/easylistczechandslovak#60]
http://s30.postimg.org/c7q457wg1/screenshot_17.png

...
@@||lichess1.org/assets/javascripts/chart/advantage.js?v=1680 @@||lichess1.org/assets/javascripts/chart/advantage.js?v=1681 @@||lichess1.org/assets/javascripts/chart/advantage.js?v=1682
...

pls fix it,...

**Comment by vobruba-martin** [comment]
Fixed in f0ac4433ec49e82b0c3c15c73cadc6a43e2231ab
