### ISSUE TITLE
Kupi.cz Antiadblock

### ISSUE THREAD

**Issue by pRWMu6NyS126WTP6ZvZhOYTv4zqjitpLiyK7Xy** [tomasko126/easylistczechandslovak#62]
Hi,

it's seems that kupi.cz started using an anti adblock. It looks similar to the one used on games.tiscali.cz.

This rule should block obfuscated equivalent of http(s)://i.imedia.cz/json, at least for now.
```
! kupi.cz
||kupi.cz/*/json
```

**Comment by Aslanex** [comment]
Added to the list, thanks.
