### ISSUE TITLE
root.cz

### ISSUE THREAD

**Issue by novjan** [tomasko126/easylistczechandslovak#66]
Nefunguje galerie (překlik foto), jelikož to blokuje potřebný script.
https://www.root.cz/galerie/ubuntu-17-10-artful-aardvark-vyvojova-verze-s-gnome

**Comment by tomasko126** [comment]
@novjan S aktuálnymi filtrami a použitím uBlocku daná galéria funguje. Vyskytuje sa stále tento problém na vašej strane?

**Comment by novjan** [comment]
@tomasko126 Už je to ok, díky
