### ISSUE TITLE
idnes.cz

### ISSUE THREAD

**Issue by gotitbro** [tomasko126/easylistczechandslovak#67]
Leftover ad elements above the header and ads on pages on http://www.idnes.cz. Anti adb warning is also displayed on some subdomains.

**SS:**
https://i.imgur.com/TUaczC8.png (**_Leftover ad elements_**)
https://i.imgur.com/FeNnY9A.png [**_Anti adb_**]
https://i.imgur.com/FuvrYU4.png (**_Ads_**)

**Error URL:**
http://zpravy.idnes.cz/macron-volby-francie-0ri-/zahranicni.aspx?c=A170616_101056_zahranicni_bur
http://technet.idnes.cz/google-translate-neural-networks-dlq-/sw_internet.aspx?c=A170418_224649_sw_internet_pka (Anti adb/ads)

Anti adb can be resolved by: `@@||1gr.cz/reklama/banner.js$script,domain=idnes.cz`
Leftover ad elements and ads can be hidden by: 
```
idnes.cz##body > div#main > table[id][class]
idnes.cz###space-g
```

There are some ads loaded on http://ona.idnes.cz. Please look into these.

Further info about the issue: https://github.com/uBlockOrigin/uAssets/issues/462

**Comment by Aslanex** [comment]
Thanks, filters added.
