### ISSUE TITLE
novinky.cz

### ISSUE THREAD

**Issue by minimum22** [tomasko126/easylistczechandslovak#70]
reklamy od nevidím do nevidím, díky.

**Comment by pepablock** [comment]
souhlasim, vsude reklamy.
pro ublock filter zablokuje vsechny reklamy na strance:
`||novinky.cz/*/json$xmlhttprequest,first-party`
_reference https://github.com/uBlockOrigin/uAssets/issues/815_

**Comment by Aslanex** [comment]
Díky za filtr, přidáno do seznamu. Obecně používané pravidlo pro všechny Adblocky je
`||novinky.cz/*/json$xmlhttprequest,~third-party`

**Comment by r2308145** [comment]
@pepablock filtr jsem použil a žádná reklama nezmizela..

**Comment by pepablock** [comment]
@r2308145 fungovalo to jeden den a pak prestalo, nevim jestli neco zmenili nebo ne.

kdyz pridam tyto filtery, tak nevidim zadne reklamy. slo by je pridat do seznamu prosim?
```
novinky.cz##script:inject(abort-on-property-write.js, AdBlockTest)
||novinky.cz/*adblock
||novinky.cz/*banner
novinky.cz###adTopsponsor
novinky.cz###adTopBigsponsor
novinky.cz##iframe[src*="rtbimp"]
novinky.cz##a[href*="clickthru"]
novinky.cz##[id^=im-]
novinky.cz###adComm
novinky.cz###adTopprodukt
```

**Comment by pepablock** [comment]
@r2308145 ty filtry jsem nevytvoril ja, kredit jde @mapx- viz. https://github.com/uBlockOrigin/uAssets/issues/815#issuecomment-342505297

**Comment by r2308145** [comment]
@pepablock ale na některých podstránkách novinek.cz na mě reklama zase vyskočila,  navíc se do toho výčtu přidalo i aktualne.cz

**Comment by r2308145** [comment]
hele já tam často taky nechodim, jenom mě to štve, protože když jsem zkusil ublock v prohlížeči Edge, tak nikde ani jedna reklama..

**Comment by Aslanex** [comment]
Novinky.cz bohužel používají různé složité metody, díky kterým dokážou někdy adblock obejít a zároveň stěžují práci těm, kdo píší pro adblock filtry. Z pohledu uživatele často výrazně pomůže vypnout pro daný web cookies.

Zmíněné filtry byly přidány, díky.

**Comment by lukasojd** [comment]
Na té stránce moc adblock nefunguje ;) 

![screenshot-2017-11-11 uz zadne damy a panove s tradicnim oslovenim konci i metro v new yorku 1](https://user-images.githubusercontent.com/3088025/32692908-fef2a40c-c720-11e7-8da7-ddffe3c28455.png)
![screenshot-2017-11-11 uz zadne damy a panove s tradicnim oslovenim konci i metro v new yorku](https://user-images.githubusercontent.com/3088025/32692909-06eae21e-c721-11e7-99ee-35dc43a1282d.png)
kreslí ty reklamy na canvas

**Comment by vobruba-martin** [comment]
Zatim jsem neprisel na duvod, ale neco v mistnich pravidlech neguje pravidla pro `novinky.cz`. Vytvoril jsem si tato pravidla:

```
novinky.cz##iframe
novinky.cz##a[href*="clickthru"]
novinky.cz##div[id^="adform"]
```

Jakmile ale zapnu CZ/SK EasyList, tak tato pravidla prestanou fungovat.

**Comment by minimum22** [comment]
Nějaké špatné pravidlo ničí css----
![obrazek](https://user-images.githubusercontent.com/27847062/32993353-16e46a50-cd57-11e7-8c94-42fa14eef072.png)

**Comment by vobruba-martin** [comment]
To je zpusob, jakym novinky asi bojuji proti blokovani reklam. Jakmile dojde k nejake detekovane blokaci, tak jejich skript zrusi jejich vlastni CSS a stranka je pak bez stylu. Je to ale nejspis vazane jen na nejake reklamy, protoze se to neprojevuje vzdy. Je treba ted vidim web vporadku :-/ . Dokazal jsem to uz driv nasimulovat, kdyz jsem si u sebe nechal kompletne zablokovat `subdocument` requesty.

**Comment by teala12** [comment]
Koukal jsem se na ty novinky.cz a vubec na fungovani adblocku plus, a pochopil jsem, ze uplne nejlip je blokovat primo dotazy, ktere nacitaji reklamu, (podle url) a ne az nasledne schovavat DIVy a linky a pod.
 (takze se stejne ceka nez se reklama nacte). A krasne mi ted fungujou tyto filtry:

||novinky.cz/*/?bn=$script
||novinky.cz/*?d=*&f=
||novinky.cz/*%2F%2Fi.imedia.cz
||novinky.cz/*%2F%2Fwww.novinky
||novinky.cz/*/sos/*
novinky.cz##.separatorLine+div
szn.cz/*v_12/vd

Normalne pri vzpnutem easylist czech+slovak, jsem si pridal jen tyhle jako custom, a novinky.cz jsou bez reklam. Nic se ani nenacte. Ten posledni filtr blokuje nacitani video reklamy, kontroloval jsem to s ostatnima videama, a tz jsou OK.

**Comment by vobruba-martin** [comment]
Vyzkousel jsem tyhle pravidla taky pri vypnutem CZ/SK easylistu a podle logu mi ani jedno nezablokovalo jedinou reklamu. Zkousel jsem ale jen nekolik reloadu na HP, ale reklamy byly normalne videt. Nemas tam jeste nejaky filtr?

Kazdopadne souhlasim, ze by bylo idealni blokovat requesty primo, ale u nekterych dojde k tomu smazani CSS, protoze to web detekuje.

**Comment by teala12** [comment]
Ono to je tim, ze se ty filtry tady asi spatne ukazou kvuli markdown formatovani.
Tady jsou k videni tak jak maji vypadat, a funguji mi na 100% 
https://github.com/teala12/abp-filters/blob/master/novinky.txt

vsimnul jsem si, ze jsi pridal pravidlo
||szn.cz$image,domain=novinky.cz

ale tam odtud by to chtelo blokovat i video, nejen $image

**Comment by vobruba-martin** [comment]
Ja tedy s aktualnimi filtry taky nevidim zadnou reklamu a i videoreklamy se mi preskakuji. A to zadne jine filtry aktivni nemam.

Tobe se zobrazuje nejaka reklama, kterou to neblokuje?

**Comment by pepablock** [comment]
FF 57 + uBlock Origin 1.14.18
videoreklamy porad vidim, ale jinak jinde reklamy nevidim.
<img width="1680" alt="01" src="https://user-images.githubusercontent.com/29940017/33008835-0c38d4fa-cdd5-11e7-81a6-d2bbf70292e6.png">
<img width="1680" alt="02" src="https://user-images.githubusercontent.com/29940017/33008837-0c5754de-cdd5-11e7-8e67-ec937acbe8a1.png">

**Comment by teala12** [comment]
Ted jsou novinky bez reklam, ale vcera vecer se mi ukazovala pod clankem videoreklama (ne pred videem) proste pod clankem a kdyz se na ni najelo mysi, tak se pustila nahlas. Hrozny. 
Na tu jsem psal to pravidlo 
`szn.cz/*v_12/vd`

Jinak ted vidam reklamy pred videem.

**Comment by vobruba-martin** [comment]
Tak problem byl u me. Videa se mi nezobrazovala nejspis proto, ze jsem byl prihlasenej. Po odhlaseni uz je vidim taky. Posilam PR.

**Comment by lukasojd** [comment]
![screenshot-2017-11-23 novinky cz nejctenejsi zpravy na ceskem internetu](https://user-images.githubusercontent.com/3088025/33189915-6e8fcb96-d09f-11e7-8ee7-7344f4af67bd.png)

![screenshot-2017-11-23 novinky cz nejctenejsi zpravy na ceskem internetu 1](https://user-images.githubusercontent.com/3088025/33189922-84298ec4-d09f-11e7-8266-8da18f4c99b0.png)

**Comment by pepablock** [comment]
tak jsem zkusil vykouzlit nejaky pravidla, ale jelikoz to mu az zas tak nerozumim, tak nevim jestli to je funkcni 100% a nerozbije to nejaky casti webu.

obcas se mi stane, ze na me vyskoci to "oko" nahore, kdyz pridam `www.novinky.cz###counterWrpBranding`, tak zmizne, dalsi problem je ten background, kterej obcas je a nekdy neni, tak jsem zkusil `www.novinky.cz##html > body:style(background:none!important;)`, ale nevim jak moc je to funkcni, zatim jsem background nevidel od ty doby co jsem to pridal.
<img width="1463" alt="screen shot 2017-11-25 at 1 50 25 pm" src="https://user-images.githubusercontent.com/29940017/33230699-adac4904-d1e8-11e7-9e46-b6ba756e46d5.png">


napr. kdyz jdu na `https://www.novinky.cz/vanoce/` tak vidim reklamu mezi clanky 
<img width="651" alt="screen shot 2017-11-25 at 1 43 19 pm" src="https://user-images.githubusercontent.com/29940017/33230588-aa2581f8-d1e6-11e7-91f8-fe0ab9310fa0.png">
kdyz pridam tohle pravidlo, tak reklama zmizi, `www.novinky.cz###adPrarticle`
