### ISSUE TITLE
Chbějící text na technet.idnes.cz

### ISSUE THREAD

**Issue by engycz** [tomasko126/easylistczechandslovak#71]
Např na stránce https://technet.idnes.cz/ngts-1b-horky-jupiter-cerveny-trpaslik-dye-/tec_vesmir.aspx?c=A171031_221649_tec_vesmir_kuz je 

místo "nemohou vznikat kolem tak malých hvězd"
jen "nemohou vznikat kolem tak hvězd"

Problém je v intext.lookit.cz, který se musí zakázatm protože mění stránku a přidává odkaz na bbelements
||intext.lookit.cz/*$domain=idnes.cz

**Comment by vobruba-martin** [comment]
Problem je toto pravidlo `@@||idnes.cz$generichide,genericblock`, ktere na cele idnes.cz domene a subdomenach rusi blokovani nacitanych skriptu, takze pak pravidlo `||intext.lookit.cz^$third-party` nema zadny efekt.

@Aslanex je nejaky duvod, pro existenci toho pravidla? Vzhledem k tomu, ze do commitu f6f573ccbc42e8296474f8c0c34727ada55ab70c nepises moc detailu, tak nelze rict, co to pravidlo melo prinest :-(

**Comment by Aslanex** [comment]
Pravidla se specifikovanou doménou se genericblock netýká, přidal jsem tedy první pravidlo do seznamu, díky za upozornění. Smyslem generichide a genericblock bylo pravděpodobně zabránit tomu, aby Idnes rozpoznal zapnutý Adblock a blokování různými způsoby obcházel.

**Comment by vobruba-martin** [comment]
Asi mi neco unika. Proc tedy na tento problem nefunguje jiz drive specifikovane pravidlo `||intext.lookit.cz^$third-party`, ktere je, zda se, ignorovano?

Viz https://github.com/tomasko126/easylistczechandslovak/blob/master/filters.txt#L505?

Kdyz totiz zavedu pouze toto pravidlo a vypnu CZ/SK EasyList, tak je dany skript uspesne zablokovan.

**Comment by Aslanex** [comment]
Genericblock se vztahuje na obecná pravidla, když tam tedy určíme doménu, už to není obecné pravidlo, kdežto v druhém případě zde konkrétní doména určena není.

**Comment by vobruba-martin** [comment]
Aha diky, uz to chapu ;-)
