### ISSUE TITLE
zive.cz, novinky.cz, isport.blesk.cz, super.cz atd

### ISSUE THREAD

**Issue by r2308145** [tomasko126/easylistczechandslovak#73]
všude reklamy..

**Comment by r2308145** [comment]
csfd.cz

**Comment by r2308145** [comment]
tento filtr by měl fungovat pro živě.cz a isport.cz:
`isport.blesk.cz,zive.cz##script:inject(addEventListener-defuser.js, DOMContentLoaded, cncAd.adlblock)
isport.blesk.cz##.ads-in`

převzato z https://github.com/uBlockOrigin/uAssets/issues/824

**Comment by Aslanex** [comment]
Filtry přidány, díky.

**Comment by pepablock** [comment]
pro csfd.cz funguje: 

```
csfd.cz##.ad-pmg
||video.csfd.cz/files/videos/*.webm$media,first-party,redirect=noopmp3-0.1s
```

viz. https://github.com/uBlockOrigin/uAssets/issues/824

**Comment by Aslanex** [comment]
díky

**Comment by r2308145** [comment]
[zive.cz](https://www.zive.cz/clanky/novy-firefox-quantum-slibuje-dabelskou-rychlost-a-malou-spotrebu-ram/sc-3-a-190498/default.aspx?artcomments=1) uz zas nefunguje

![screenshot-2017-11-15 diskuze novy firefox quantum slibuje dabelskou rychlost a malou spotrebu ram](https://user-images.githubusercontent.com/33419338/32849294-0563f1c2-ca2f-11e7-8ace-a0f4e921092f.png)

**Comment by tomasko126** [comment]
@r2308145 reklamy na mobilmania.cz a zive.cz znovu zablokované  v b41e211dc07f6c5501a65b313a7818743dbed340.

**Comment by r2308145** [comment]
super!

**Comment by WalrusInAnus** [comment]
Na Novinkách reklama úplně všude :( Banner nahoře, banner v textu, tři! svislé bannery na pravé části.

**Comment by krejmaj** [comment]
Pokud se na konkretni web neprihlasujete (nepisete na nej komentare apod.) je zdaleka nejsnazsi zablokovat a nasledne smazat pro danou domenu cookies. 

Jinak by to chtelo napsat script ktery by rozbil praci s adb cookie a poslat pull request na skript injection ( https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt )

**Comment by vobruba-martin** [comment]
Momentalne v issue #115 resime rozdeleni filtru, abysme mohli pouzivat pravidla pro uBlock a nerozbijelo to fungovani s ABP.

Prozatim vyresim, aby Novinky nebyly rozbite. Pak budeme moct psat slozitejsi pravidla.

**Comment by novjan** [comment]
@vobruba-martin Nová pravidla pro blokování rozbijí tuto stránku:
`https://tvprogram.idnes.cz/tvprogram.aspx`

**Comment by vobruba-martin** [comment]
@novjan Ja to mam rozbity i s vypnutym blokatorem... Po reloadu se to obvykle spravi bez ohledu na blokator.

**Comment by novjan** [comment]
@vobruba-martin Hmm zajímavé. Mě to nefunguje jen s blokátorem. Bez něj to je ok. No nic. Kašlu na to :)

**Comment by vobruba-martin** [comment]
Pridal jsem, co jsem nasel, takze zaviram.

**Comment by WalrusInAnus** [comment]
Já teda na hlavní straně Novinek pořád vidím nejmíň tři bannery.
