### ISSUE TITLE
Odblokace lišty myGIVT 

### ISSUE THREAD

**Issue by hrncir39** [tomasko126/easylistczechandslovak#75]
Dobrý den, do adblocku byla přidána blokace lišty myGIVT - jedná se o náš projekt - mygivt.com, se kterým momentálně expandujeme do Rakouska a Polska. Je to funkční toolbar, který si dané weby dobrovolně umísťují na své stránky, aby je jejich fanoušci mohli podporovat nákupy přes internet. Momentálně je lišta umístěná na cca 70 webech v ČR (zpravidla velké a středně velké sportovní kluby) a celkový trraffic těchto webů je několik milionů unikátů měsíčně. Chápu, že ste možná dostali nějaké podněty, ale jsem si jistý že jde v rámci toho zásahu o setiny promile. Blokace docela výrazně poškozuje jak náš projekt, tak samotné kluby, které možnost nákupů samy promují - a běžný uživatel si nespojí adblock a tuto aplikaci, takže ji prostě na stránkách nenajde a píše do klubu atd. Prosím o vaše vyjádření - díky moc.

**Comment by vobruba-martin** [comment]
Pripojim zde komentar z meho commitu ccbd27fa1a4fa753ec58e46cad5cc12676cf0b8d

Z meho pohledu je to reklama jako jakakoliv jina. Duvody, proc jsem se rozhodl vytvorit pozadavek o zacleneni, jsou:
1) Vas toolbar zbytecne prodluzuje nacteni cele stranky.
    - Nekdy to trva i 10-20s a nekdy pomuze jen reload, protoze se nedari navazat SSL spojeni s vasim serverem. Pravdepodobne se to deje jen v nejakych spickach, protoze pak se skript nacte okamzite.
    - Tim, ze se nenacita asynchronne, tak blokuje zobrazeni cele stranky (v Chrome pak vidim jen bilou stranku a dole v rohu "Cekani na mygivt.com...").
2) Animace, kdy toolbar prejede temer pres polovinu stranky, mi uz nekolikrat zablokovala klik, protoze toolbar byl momentalne na miste, kde jsem chtel kliknout.

**Comment by Aslanex** [comment]
Asi je pravda, že to není úplně reklama z podstaty, zatím tedy odblokovávám. Nutno ale uznat, že načítání cizích skriptů stránky zpomaluje a jedním z cílů Adblocku je právě načítání zrychlit, bylo by proto z vaší strany rozumnější, kdyby web na vaši službu odkazoval jen svými skripty. Ale to je těžké, chápu.

**Comment by HerKulez** [comment]
Takže až sem napíše nějaká reklamka tak jí taky odblokuješ všechny banery? Nebo až sem napíše někdo z idnesu tak taky zrušíš všechny jeho filtry? Všechny weby si dávají reklamu na stránky dobrovolně! V čem se tahle reklamní lišta liší od ostatního balastu kterej chceme blokovat a kvůli kterýmu si instalujem adblock plugin?

**Comment by Aslanex** [comment]
Je rozdíl mezi reklamou a externí službou. Taky neblokujeme komentářové pluginy jako Disqus, přestože si tím dělají na webech reklamu. MyGIVT je někde na pomezí těchto dvou možností. Je samozřejmě těžké určit, kde je ta hranice, a proto zde máme toto vlákno, kde můžete vyjadřovat svůj názor na tuto lištu, a pokud budou převažovat hlasy pro zablokování, klidně ji zase zablokuji.

**Comment by vobruba-martin** [comment]
Ta hranice je, myslim, jasne definovana EasyListem jako: "[the promotion of third party content in return for goods or services](https://easylist.to/2011/07/11/the-definition-of-advert-and-link-exchange-policy.html)".

Z meho pohledu to srovnani s komentarovymi pluginy kulha. Ty sice nabizeji sve sluzby, ale weby tim promuji jen samy sebe, coz je jedna z vyjimek, kdy k blokaci nema dojit: "[Self-promotion should not be specifically removed by EasyList, although equally should not be whitelisted if it is blocked.](https://easylist.to/pages/policy.html)"

Tahle lista ale promuje X dalsich sluzeb na zaklade nejakeho affiliate programu. Tedy spada do definice reklamy a vztahuje se tedy na ni pravidlo "[Adverts must be blocked regardless of the reasons for their presence or the purpose that the money raised ultimately serves.](https://easylist.to/pages/policy.html)". Nebo jak s tou listou dochazi k promovani sebe sama? Ta lista ma za ukol jen vydelavat sobe, webu a dalsi strane, na kterou odkazuje, nic vic.

Navic chovani te listy je v rozporu s chovanim [akceptovatelnych reklam](https://adblockplus.org/acceptable-ads#not-acceptable-ad):
- Animated ads
- Expanding ads

Spatne vyreseny zpusob nacitani te listy blokujici zobrazeni celeho webu je uz jen tresnickou na reklamnim dortu.

**Comment by Aslanex** [comment]
Dobře, to je rozumné podrobné vysvětlení, proč by měla být blokována. Filtr tedy opět přidávám a omlouvám se za zmatky.

**Comment by PeterPalus** [comment]
Pánové, díky všem za rozumnou diskuzi. Chápu, že náš projekt stojí na hranici nebo jí (dle některých názorů) překračuje, ale všichni se asi shodneme, že rozdíl mezi lištou a reklamním bannerem je poměrně jasný. Dovolte mi pár poznámek: 

1. Stránky, na kterých ta lišta je, její používání aktivně promují. Brand myGIVTu je záměrně potlačen, je to v podstatě SaaS, který si od nás kluby a organizace pronajímají a používají jej pro své účely (např.: [http://www.hc-havirov.cz/clanek.asp?id=-Vzpomente-si-pri-nakupech-na-nas-a-udelejte-Vesele-Vanoce-i-svemu-klubu-3153](url). Z jejich strany tak vlastně bráníte používat jejich vlastním uživatelům jejich službu. 

2. Ze své podstaty se nejedná o reklamu. Cílem není promovat dané eshopy a už vůbec ne náš vlastní brand, ale umožnit svým fanouškům podporovat klub novým způsobem (tj. využívat ten nástroj).

3. Jedná se o zcela novou službu a produkt, opravdu to nikdo jiný na světě takto nedělá a je proto, jasné, že to nemohou dopředu postihovat žádná pravidla (a je docela obtížné se k nim upínat zpětně).

4. Tímto čínem vlastně, bohužel, brzdíte projekt, který momentálně expanduje z ČR a začíná být úspěšný v Rakousku a Polsku (další země budou následovat). Není to spíše něco, co by se mělo podporovat? :)

Prosím, pokud mohu jakkoliv pomoci tomu, aby lišta přestala být blokována, velmi rád zodpovím jakékokoliv dotazy. 

Díky. 

Peter Páluš, CEO GIVT.cz

**Comment by vobruba-martin** [comment]
Lista pro affiliate program je porad jen reklama i kdyz se to snazite libive zaobalit a ohybat vsemi smery.

**Comment by PeterPalus** [comment]
@vobruba-martin 

Martine, já se vás snažím pochopit, ale ocenil bych, kdybyste trochu argumentoval. Já se o to pokouším docela poctivě. Váš commit se věnoval technické stránce, tzn. že kdyby se to "načítalo" jinak, je to v pořádku? Nebo je to reklama? Blokujete třeba widgety darujme.cz? [http://kous.cz/wp-content/uploads/2016/05/Widget.jpg](url) Je to stejná služba s tím rozdílem, že u nás fanoušci a podporovatelé přispívají a nic je to nestojí.

**Comment by PeterPalus** [comment]
@vobruba-martin 

Martine, ocenil bych, kdybyste se trošku pokusil argumentovat. Já se o to opravdu snažím. V commitu jste zmínil technické problémy, nyní píšete o reklamě. Blokujete třeba widgety darujme.cz? Tohle je stejné, jen s tím rozdílem, že fanoušci mohou podporovat bez toho, aby je to cokoliv stálo. Díky.

**Comment by vobruba-martin** [comment]
A na co chcete, abych reagoval? Ja jsem tady vypsal duvody, proc by podle me mela byt lista blokovana a vy argumentujete tim, ze vas unikatni affiliate program neni reklamou i kdyz podle EasyListu do te definice spada. Ze me k vytvoreni PR dokopaly az problemy technickeho razu, na tom nic nemeni.

Kdyz budu chodit na darujeme.cz a budou tam na me vyskakovat reklamy, tak zalozim PR i pro jejich web. Stejne jako to muze udelat kdokoliv jiny (o tom je opensource) a budeme to resit v samostatnem vlakne.

**Comment by PeterPalus** [comment]
@vobruba-martin 

Prosím, já ten EasyList četl asi třikát a pořád nechápu, kam podle vás spadáme. Partneři mají lištu. Část z nich nám platí za to, že jí mají. My jim nic nedáváme, dokud nepřispějí jejich fanoušci, kteří to udělají z vlastní vůle. Teda pokud nepřijdete vy a nerozhodnete, že vlastně nemohou :). Bavme se konkrétně. Díky.
