### ISSUE TITLE
Falešně pozitivní blokace na aktualne.cz

### ISSUE THREAD

**Issue by lukasojd** [tomasko126/easylistczechandslovak#76]
Ahoj, 
mohl by někdo pořešit bílou stránku, na aktualne.cz. Je tam nastavené pravidlo co skrývá všechny elementy na stránce... To asi není správné chování adblocku...  Reportuju to celý týden.

**Comment by lukasojd** [comment]
Jedná se o tento řádek
https://github.com/tomasko126/easylistczechandslovak/blob/master/filters.txt#L722

**Comment by Aslanex** [comment]
Opraveno, díky za upozornění.
