### ISSUE TITLE
DVTV.cz (video Aktuálně.cz)

### ISSUE THREAD

**Issue by r2308145** [tomasko126/easylistczechandslovak#91]
reklamy na stránce i ve videu, viz:
![bez nazvu](https://user-images.githubusercontent.com/33419338/33118177-559b1120-cf6b-11e7-97af-a9364c5f775e.png)

**Comment by novjan** [comment]
aktualne.cz jako takové je plné reklam

**Comment by Kisuke-CZE** [comment]
Netusim cim to, ale ja to plne reklam nemam...

Kazdopadne me pomohlo na nektere reklamy:
`aktualne.cz##script:contains(addEventListener)`
Funguje ale jen v kombinaci Firefox + uBlock Origin (nebot Google tuhle funkcionalitu z Chromu uz davno odebral, aby mu nahodou nekdo spolehlive neblokoval reklamu)

Kdyztak kouknete pro inspiraci do mych filtru tady na githubu. Jsou sice trosku hrubsi (obcas rozbijou nejakou nepodstatnou vec na webu), ale funguji a me to tak vyhovuje, stejne tak znamym, kvuli kterym sem to dal sem.
