### ISSUE TITLE
idnes.cz, novinky.cz

### ISSUE THREAD

**Issue by MekliCZ** [tomasko126/easylistczechandslovak#93]
Na některých stránkách zpravodajských serverů, třeba na https://ekonomika.idnes.cz/coop-zavreni-prodejen-ztraty-d21-/ekonomika.aspx?c=A171122_160933_ekonomika_are se po načtení stránky zablokují CSSka, takže je stránka jen plaintext. Zatím se nám podařilo to vysledovat na avmania.e15.cz, idnes.cz a novinky.cz.

**Comment by vobruba-martin** [comment]
Na novinkach tenhle problem byl odstranenej pred 3 dny. Mas aktualni filtr? Jaka pravidla blokovani jsou aktivni, kdyz se ti to stane?

**Comment by MekliCZ** [comment]
@vobruba-martin Zrovna novinky se nestaly mně, ale stěžoval si nám někdo do Mozilla.cz, že za to může nový Firefox. Včera jsme zjišťovali, co za to vlastně může, a člověk co to testoval tak vytvářel nový profil a instaloval čistě adblock, takže filtry by mít aktuální měl.

**Comment by vobruba-martin** [comment]
Aktualni filtry muze vyzkouset pomoci teto URL `https://raw.github.com/tomasko126/easylistczechandslovak/master/filters.txt`. Problem je, ze kdyz se to naklika jen ciste pomoci adblocku, tak tam muzou byt az 4 dny stare filtry.

**Comment by r2308145** [comment]
Mě by zajímalo jak je možné, že v Edgi + uBlocku ve výchozím nastavení (bez jakýchkoli přidávaných filtrů) nevidím na nejčastějši zmiňovaných webech (novinky, idnes, isport, aktualne atd.) ani jednu reklamu, zatímco ve Firefoxu + uBlocku je to neustálý boj

**Comment by WalrusInAnus** [comment]
Novinky jsou absolutně rozsypané. Není to plaintext, ale stránka je úplně rozházená.

**Comment by vobruba-martin** [comment]
Jo, novinky pravidelne upravuji HTML tak, aby to lidem s blokatorem zneprijemnily a zaroven byly videt reklamy... Kazdopadne tohle tema zaviram, protoze se tyka neceho jineho.

**Comment by Vict0rC** [comment]
Od vcera se mi opet po nacteni stranky blokuji css na techto webech. BL mam aktualni.

**Comment by r2308145** [comment]
mozna neco zmenili, take mi par stranek blblo..
